### ISSUE TITLE
Cart PUT request on item quantity updation is adding the quantity to last quantity not updating it as new

### ISSUE THREAD

**Issue by sp93s** [magento/devdocs#1033]
Feedback on page: /guides/v2.0/rest/list.html

**Comment by keharper** [comment]
I need more details about what you're trying to do. Would you provide the call, payload, and response?

**Comment by sp93s** [comment]
let you added a particular item in cart (quantity was 3).Now if I want to update the quantity of that particular item by  PUT  /V1/carts/mine/items/:itemId request now let I send this items quantity 5, then finally the updated quantity of that particular item in cart becomes 8 instead of updating to 5 .

**Comment by keharper** [comment]
What version are you using? I can't replicate this on 2.1.3

1. Add 3 items to a cart.
```
POST V1/carts/mine/items
{
  "cartItem": {
    "sku": "WS12-M-Orange",
    "qty": 3,
    "quote_id": "6"
  }
}
```

Response

{
  "item_id": 22,
  "sku": "WS12-M-Orange",
  "qty": 3,
  "name": "Radiant Tee-M-Orange",
  "price": 22,
  "product_type": "simple",
  "quote_id": "6"
}

2. Change the number of items to 5.

```
PUT 1V1/carts/mine/items/22
{
  "cartItem": {
    "qty": 5,
    "quote_id": "6" }
  }

```

Response

```
{
  "item_id": 22,
  "sku": "WS12-M-Orange",
  "qty": 5,
  "name": "Radiant Tee-M-Orange",
  "price": 22,
  "product_type": "simple",
  "quote_id": "6"
}
```

**Comment by sp93s** [comment]
PUT rest/default/V1/carts/mine/items/138
{
  "cart_item": {
    "quote_id": "17",
    "sku": "24-WB04",
    "qty": "2"
  }
}

RESPONSE 

{
  "item_id": 138,
  "sku": "24-WB04",
  "qty": 16,
  "name": "Push It Messenger Bag",
  "price": 45,
  "product_type": "simple",
  "quote_id": "17"
}

**Comment by sp93s** [comment]
version 2.0

**Comment by jeff-matthews** [comment]
I don't think this is a documentation-specific question @keharper. Please close if there's no doc impact.

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
