### ISSUE TITLE
Magento 2 certain version compatibility changes within days

### ISSUE THREAD

**Issue by anujeetphj** [magento/devdocs#1040]
Feedback on page: /guides/v2.1/install-gde/system-requirements-tech.html

I'm using Magento 2.1.3 version . My reason to choose the latest version was to have all the patches to the issues fixed till now. But it's been just a month that I've started using this in my project suddenly on the requirements page I see that that my Magento version requires different php version though it ws not mentioned on the day I installed it!

Don't you think you should resolve issues other than giving a list of supported versions that even changes within days.

Completely dissatisfied with Magento 2.1

**Comment by xcomSteveJohnson** [comment]
System requirements weren't changed; can you clarify where you saw the PHP version originally? You say "suddenly" you see a different PHP version than you saw "the day you installed it". I'm not sure where the discrepancy is coming from. Thanks!

**Comment by anujeetphj** [comment]
When I installed the magento 2.1.3 version the CLI commands were working
fine and that time I had the same PHP version I'm having now. Since today
morning I am getting warnings while executing CLI commands for mcrypt
functions. From where all these warnings are coming suddenly?

With Best Regards

Anujeet Kaur

**Comment by xcomSteveJohnson** [comment]
Please provide these details:

*  PHP version (do you have more than one installed?)
*  Error message text

Thanks

**Comment by anujeetphj** [comment]
My PHP version is 7.1.1
Magento 2.1.3

And the error is in whole Magento/framework....Crypt.PHP file for all
mcrypt/mdecrypt functions

With Best Regards

Anujeet Kaur

**Comment by anujeetphj** [comment]
The errors are for depreciated functions

With Best Regards

Anujeet Kaur

**Comment by xcomSteveJohnson** [comment]
Magento does not support PHP 7.1. Did the system requirements page confuse you on that point?

We're considering changing that page. I apologize for the confusion it caused.

**Comment by anujeetphj** [comment]
Which PHP versions can support my current Magento and later versions?

With Best Regards

Anujeet Kaur

**Comment by xcomSteveJohnson** [comment]
Assuming you want to stay with PHP 7:

All 2.1.x versions support: 7.0.2, 7.0.6–7.0.x 

_Not_ supported by any 2.1.x version:

PHP 7.1
PHP 5.5

**Comment by xcomSteveJohnson** [comment]
Even though PHP 7.1 is not supported, I suggest you raise an issue in the [Magento 2 GitHub](https://github.com/magento/magento2/issues) because it doesn't seem like you should have been able to install Magento in the first place.

**Comment by anujeetphj** [comment]
And can you please explain why I'm getting the warnings from today?


Will skippings warnings for depreciated functions cn solve the issue once
or the compatibilty issue may cause other problems in the future as well?

With Best Regards

Anujeet Kaur

**Comment by xcomSteveJohnson** [comment]
[PHP documentation](http://php.net/manual/en/migration71.deprecated.php)

**Comment by anujeetphj** [comment]
Thanks if I will override the file in which I'm gettings errrors with my
own custom file and use replacements for depreciated functions. Will it
work?

With Best Regards

Anujeet Kaur

**Comment by xcomSteveJohnson** [comment]
I'm not sure, I'm sorry. You can ask this on stackexchange or the Magento 2 GitHub.

**Comment by orlangur** [comment]
Hi again, @anujeetphj,

> can you please explain why I'm getting the warnings from today?

This happened because of PHP configuration change on your side as explained [here](https://github.com/magento/magento2/issues/8569#issuecomment-280074808).

> Will skipping warnings for deprecated functions can solve the issue once
or the compatibility issue may cause other problems in the future as well?
> if I will override the file in which I'm getting errors with my
own custom file and use replacements for deprecated functions. Will it
work?

Skipping warnings in general cannot cause any troubles by itself. In particular, deprecated `mcrypt_*` functions work in PHP 7.1 just like in PHP 7.0, only trigger `E_DEPRECATED` notice. So, if you suppress these warnings it should work fine until PHP 7.2, where these functions will be removed.

Note that there are other [backward incompatible changes](http://php.net/manual/en/migration71.incompatible.php) between PHP 7.0 and 7.1 which may cause malfunction of your Magento instance in some scenarios. So, you may use PHP 7.1 with some tweaks like `E_DEPRECATED` suppressing for development purposes but you shall not use it in production until PHP 7.1 is officially supported.

Hope it makes situation completely clear to you.

**Comment by tanberry** [comment]
Thanks @orlangur !!

**Comment by xcomSteveJohnson** [comment]
No comments or info for >14 days, closing. Feel free to open another issue if there's something we can help you with.
