### ISSUE TITLE
Misleading Page Title

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#1049]
The following page

> http://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-pg-cache.html

uses the title

> Use Redis for page caching

However, the listed configuration

    'cache' =>
    array(
       'frontend' =>
       array(
          'default' =>
          array(
             'backend' => 'Cm_Cache_Backend_Redis',
             'backend_options' =>
             array(
                'server' => '127.0.0.1',
                'port' => '6379'
                ),
        ),
        'page_cache' =>
        array(
          'backend' => 'Cm_Cache_Backend_Redis',
          'backend_options' =>
           array(
             'server' => '127.0.0.1',
             'port' => '6379',
             'database' => '1',
             'compress_data' => '0'
           )
        )
      )
    ),

Provides a configuration that sets up Redis as **both** the engine for Magento's full page cache, as well as Magento's generic programatic cache (available via the `Magento\Framework\App\CacheInterface`.

Providing both these configurations is important.  However, the information as presented is confusing, and makes finding/realize the `Magento\Framework\App\CacheInterface` information s already present non-obvious. 

Additionally, this page

http://devdocs.magento.com/guides/v2.0/config-guide/redis/config-redis.html

lists two links

- Redis for session storage
- Redis for page caching
 
Which make is seems like a Magento developer can't use Redis as the `Magento\Framework\App\CacheInterface` storage mechanism. 

No opinion here on what the fix should be, other than the documentation should accurately reflect Magento 2's capabilities.

**Comment by xcomSteveJohnson** [comment]
I performed some cosmetic surgery on the topics. Let me know what you think.

**Comment by hostep** [comment]
If I may add some comments in here.

@xcomSteveJohnson: your changes made it a bit more clear, but it might not be enough yet.

We recently set up a new webshop with both Redis (used for Magento caching and session storage, because we are working with a loadbalanced setup) and Varnish (used for full page caching).

This means we only needed the `frontend` part of the Redis configuration from [this page](http://devdocs.magento.com/guides/v2.1/config-guide/redis/redis-pg-cache.html), since we use Varnish and not Redis for full page caching.

I think it makes more sense to actually split up the configuration example on the above page, so it is more clear that the storage of the default caching and the full page caching can be configured in a different way.

----

Also, it might be a good idea to explicitly define the `database` setting in the default caching and make sure it differs from the `database` value for both the full page caching and the [session storage example](http://devdocs.magento.com/guides/v2.1/config-guide/redis/redis-session.html).

Because not defining is the same as `'database' => '0',`.

What happened in our case, was that the hosting company who setup the Redis installation and configuration in Magento blindly copied the default examples, and that meant both the default caching and the session storage were both configured to use `database` 0.
This had as a result that when we flushed the Magento caches, the sessions were also deleted every time. So this was really bad (luckily this was detected before going in production with this webshop).

I think it would be helpful if all three of the Redis configuration examples explicitly have a different `database` value, to prevent people from blindly copy and pasting those examples which will prevent making mistakes.

My suggestion is that the default cache gets `'database' => '0',` added to its configuration example, and the session configuration is changed to `'database' => '2',`

Feel free to comment on the above change requests. And if I should create a new issue for the above requests, let me know. I think it fits in here, but if not, I'll move it to a new issue.

**Comment by xcomSteveJohnson** [comment]
@hostep Made the changes you suggest, please check. Thanks, that was very helpful.

**Comment by hostep** [comment]
@xcomSteveJohnson: alrighty, very good!

Hope this also satisfies @astorm's remarks.

**Comment by xcomSteveJohnson** [comment]
Any objections to closing this?

**Comment by jfrontain** [comment]
@astorm and @hostep, thanks for your help. We're closing this issue now, but please feel free to submit additional suggestions.
