### ISSUE TITLE
Manage Maintenance mode by IP with Varnish

### ISSUE THREAD

**Issue by franckgarnier21** [magento/devdocs#1072]
Feedback on page: /guides/v2.1/install-gde/install/cli/install-cli-subcommands-maint.html

How can we activate Maintenance mode by IPs working with Varnish ?

First I update the nginx configuration in order to retrieve the real customer IP :+1: 
    set_real_ip_from    127.0.0.1; #Put the Ip of your varnish/proxy here
    real_ip_header    X-Forwarded-For; #Put the Header that your varnish/proxy set

But how can I manage the page which is already cached by Varnish and then is not retrieved by Nginx.

It can be an issue if the site is open for a specific IP, then varnish cache these pages, then other IPs will be able to see these pages.

Many thanks.

**Comment by xcomSteveJohnson** [comment]
We might not be able to answer this question here. We'll refer this to engineering but meanwhile, have you tried asking this on the [Magento 2 GitHub issue page](https://github.com/magento/magento2/issues) or stackexchange?

**Comment by franckgarnier21** [comment]
Thanks, issue related https://github.com/magento/magento2/issues/8975

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
