### ISSUE TITLE
What happened to the sample extensions?

### ISSUE THREAD

**Issue by dunctem** [magento/devdocs#1133]
Feedback on page: /guides/v2.1/extension-dev-guide/intro/developers_roadmap.html

**Comment by keharper** [comment]
We are investigating why the repo is unavailable.

**Comment by BenSpace48** [comment]
The knock-on effect of this is some links on the dev docs are now 404ing - [example](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/custom_preprocess.html)

**Comment by tanberry** [comment]
Hi all, and thanks @dunctem  and @BenSpace48 for alerting us to the 404s. We are working on those this morning. 

Sadly, we will no longer be able to link to the sample extensions, as the decision was made to close the repository for now, until the 20+ extensions there can be systematically updated and tested with the latest versions of Magento.

We would welcome your feedback and opinion on this decision, and on any possible ideas for getting the samples updated so that we can again link to them... is it a possible community project? @piotrekkaminski

**Comment by BenSpace48** [comment]
I feel like they are a good resource to have and the dev docs don't have enough samples in my opinion, and there is proof people are using the samples. There are multiple issues already raised about this on the dev docs repo, Magento2 repo, and on https://magento.stackexchange.com/. I used them a few times whilst first learning Magento 2, especially the Sass one.

Surely the positives of samples outweigh the negatives, the more help you can give to developers new to Magento 2 the better. For frontend (and possibly backend) the skill level required to be efficient in M2 is already much higher than M1, I'm worried that new developers will be scared away from M2 as it is. In my opinion it is worth the time it would take for core devs to create some samples.

If people in the community are willing to update them I think it's better than having no samples.

**Comment by rhoerr** [comment]
Even if they were out of date, the sample modules were an invaluable teaching tool on (1) how to write M2 code, and (2) how to accomplish many of the things people need to do (that is, demonstrating how architectural pieces actually work in practice).

I would much prefer to see Magento continue an active role in creating/maintaining them over having them become entirely community-drive, but not having them at all seems like a huge loss.

Any ETA on how long it will take for the repo to be "systematically updated and tested with the latest versions of Magento" ?

**Comment by davidstillson** [comment]
The samples were pivotal in my learning for M2 development.  I'd read stuff in the devdocs, and then be like "That's cool, let's jump over to the sample repos and see how to actually do this stuff in real life."

I think it does a real disservice to not have those examples so that developers can see best practices for how a module should be put together.  Often, I wasn't installing them as is and expecting them to work, I was browsing specific files to see how to properly do something in my own code (like update my layout files, create an InstallData.php file, or setup a service interface, etc.)

**Comment by tanberry** [comment]
@davidstillson and all, we hear you loud and clear; teams here are discussing now and probably into the next day or so... we value your feedback and will get back with more info soon. We do see the value of simply looking through the code to see how things are done... that's exactly why were excited to link to them from the devdocs!

**Comment by joshuaswarren** [comment]
I think this is a great thing for maybe @maksek and Community Engineering/Community Contribution Days to tackle. Let us know how we can help. 

I have links to that repo in my soon-to-be-published book, it's in so many articles online - killing the repo off isn't a good solution. Maybe there could be a tag or release on the repo showing the Magento version the modules are written for? Because my understanding is that the modules were all written for 2.0 and not updated for 2.1. When 2.2 comes out, developers really need up-to-date samples to refer to, so they'll need to be updated again. 

I know that the sample modules aren't "docs" or part of devdocs, but I think that sample code is just as important as devdocs or a Magento U module for developers to learn Magento 2. Everyone learns best by different ways, and those sample modules really help a lot of developers and reinforce many of the concepts from devdocs with live examples. We need them.

**Comment by tanberry** [comment]
OK, great news, and thanks for everyone's feedback and patience! The sample repo is back up, with a helpful little note stating that the sample extensions were developed on 2.0.x, etc.

**Comment by BenSpace48** [comment]
Good stuff, thanks @tanberry
