### ISSUE TITLE
Screenshot Components

### ISSUE THREAD

**Issue by WileESpaghetti** [magento/devdocs#1169]
Feedback on page: /guides/v2.1/ui_comp_guide/bk-ui_comps.html

It would be nice to be able to see an example screenshot of the components.

**Comment by almarchenko** [comment]
@WileESpaghetti  Thank you for a good request!
We usually add links to the screenshots in topics describing each particular component, for example:
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-modal.html
http://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-massactions.html
In the first sections of the topics there's a link to the  Admin Design Pattern Library (MassActions), where the screenshots are present. 

But for most components the links are absent, either because of there's no topic in the Admin library, or because we missed to add a link.
I've created the internal issue Magetwo - 69649 to see where else we can add links/screenshots.

**Comment by shrielenee** [comment]
Thanks for bringing this to our attention! We are actually currently working on improving all of our UI components documentation. This is on our radar and we will consider it as we work to revise that documentation. I'll be closing this for now - so stay tuned for components docs updates!
