### ISSUE TITLE
OnOffColumn component page

### ISSUE THREAD

**Issue by RakeshJesadiya** [magento/devdocs#1219]
Feedback on page: /guides/v2.1/ui_comp_guide/components/ui-onoffcolumn.html

Hello,
When i clicked on Edit this page on GitHub on top right of page, Its redirect to 404 page not found.
Please look into it and resolve the issue as soon as possible.

Thanks.

**Comment by jeff-matthews** [comment]
This is a strange one... If you inspect the link on the page with chrome dev tools, it appears to be correct. However, if you right-click > copy the link and paste it into a text editor, you can see that the "c" in ..."ui-onoffcolumn.html" is actually encoded for come reason (e.g., ..."ui-onoff%D1%81olumn.md"). 

I suspect a bad copy/paste operation in the topic YAML front matter (i.e., `github_link:`) is responsible because manually retyping the "c" appears to fix the problem on local builds.

**Comment by jeff-matthews** [comment]
Verified changes to live site in `gh-pages` branch commit 873cd67aa887c599e81ecaec08cc294338a23cec, but the link still doesn't work and the encoding issue is still present.

**Comment by jeff-matthews** [comment]
@jcalcaben: Any ideas?

**Comment by jeff-matthews** [comment]
Nevermind @jcalcaben. @keharper verified that the link now works.
