### ISSUE TITLE
This page assumes I know where to put the code samples

### ISSUE THREAD

**Issue by noctufaber** [magento/devdocs#1226]
Feedback on page: /guides/v2.0/extension-dev-guide/extension_attributes/adding-attributes.html

This page provides sample code but doesn't offer any guidance on what the names of the files are supposed to be and where those files will be located within the directory hierarchy.  Where do I copy the code samples?

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
