### ISSUE TITLE
This page assumes I know the filename of the shipping address form.

### ISSUE THREAD

**Issue by noctufaber** [magento/devdocs#1230]
Feedback on page: /guides/v2.1/howdoi/checkout/checkout_new_field.html

The first code sample code doesn't give me a filename and path.  Where am I supposed to place this code?

Steps 2 and 3 describe including a JS mixin.  Do I need to have the JS mixin?  What if I only intend to use this in an API request?

**Comment by shrielenee** [comment]
Hey there @noctufaber - In the page you reference, in order to add your custom field to the checkout address form and access its value on the client side, you should complete all of the listed steps. If you click through to the linked plugins page, from the Step 1. section noting that you should create a plugin, it is mentioned that you add this info to the `di.xml` file.

I will also add this info to the Step 1. section so it's easier to understand. Let me know if there is anything else that would be helpful to include.

**Comment by shrielenee** [comment]
Fixed in relevant PR https://github.com/magento/devdocs/pull/3160
