### ISSUE TITLE
Information about CMS page layout handles missing

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1313]
Feedback on page: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-overview.html

The short note regarding page layout handles under the "Terms used" section doesn't mention an example of including a CMS page, which, it seems, needs a certain trick to make it work, as shown here:
https://github.com/magento/magento2/issues/10300#issuecomment-316939373
> you will need to use the url-key of the CMS page for the XML layout file.
> For example if you have a cms page with the URL Key `home` then you XML layout file would be `cms_page_view_id_home.xml`

I believe, this information is quite useful and should be added to the docs.

**Comment by bdenham** [comment]
I agree that more information about layout handles in general is needed. But I would propose an article that is dedicated to the subject: how to find them, how to use them, why they are important, code examples of usage, etc. I've added a brief reference/example of a CMS page handles in #1699 as mentioned, but much more needs to be written about layout handles in its own topic.

**Comment by shrielenee** [comment]
Thanks for bringing this to our attention. It looks like @bdenham addressed part of the issue here, by adding reference/example info via https://github.com/magento/devdocs/pull/1699. 

We are creating an internal ticket to further address the bigger issue of creating a doc page about how to find them, use them, why they are important, etc. 

Thanks again for helping out!

**Comment by bdenham** [comment]
Internal ticket number is #MAGEDOC-3124.
