### ISSUE TITLE
How to set Payflowpro payment credit card details using sales order api?

### ISSUE THREAD

**Issue by magentounit2** [magento/devdocs#1387]
Hello,

We have referred one of the Magento devdocs post related to REST API create order,

[Create Order Using Sales API](http://devdocs.magento.com/guides/v2.1/get-started/order-tutorial/order-create-order.html)

This link is working for Offline payment method.

I need to create order using **Creditcard** details.

 **I want to place order using Paypal payflow pro as payment method.** How to place order using online payment method.

Just for Test Order, I want to pass data for VISA credit card,
**card number**: 4111111111111111
**Start Month/Date**:05/2014
**Expiry Month/Date**: 10/2019
**payment_method**: payflowpro

How to place order using rest api for above info.

Any documents are available for Online Payment method **REST API** using magento 2.
Thanks.

**Comment by RakeshJesadiya** [comment]
@keharper Any Updates on this issue?

Thanks.

**Comment by keharper** [comment]
It's an issue I really want to address, but I haven't found the time to work on it. Hopefully, in the near future.

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
