### ISSUE TITLE
What to do when you cannot log in?

### ISSUE THREAD

**Issue by dufferman87** [magento/devdocs#1396]
Feedback on page: /guides/v2.1/comp-mgr/module-man/compman-start.html

What we need to know is what to do when you cannot sign into Component Manager. We installed a plugin, since that point, we can no longer loginto our account, we just get the spinning wheel "Please Wait"

The plugin supplier says its the problem of Git Hub, the hosting company says it has nothing to do with Git Hub!

We cannot do anything and its holding up our project.  

We are building a B2B site in Community Edition, once this is up and running and the client is happy with it, we will be migrating to Enterprise Edition. The website is advanced as we are fully integrated with the customers ERP system.

Any help appreciated.

Adam
![screen shot 2017-08-29 at 16 36 30](https://user-images.githubusercontent.com/10629415/29829638-cbafabb8-8cd7-11e7-8685-fe34863126c0.png)

**Comment by korostii** [comment]
> We are building a B2B site

Who's "we"? do you have any developers on you team? 
The developer would be the first person I would ask for help if such an issue would appear on my project (obviously, hosting company and plugin provider don't have any responsibilities reaching and\or fixing your project's source code).

Otherwise you're largely on your own and the documentation's repository is certainly not the place to ask for such kind of help. 
I would suggest reaching out to to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) for help. 
If someone responds, you'll likely encounter a lot of follow-up questions like "are there any errors in Magento's logs or in the browser console"

**Comment by jcalcaben** [comment]
Closing issue since it is not related to documentation.
