### ISSUE TITLE
Magento nightmare

### ISSUE THREAD

**Issue by marckatznelson** [magento/devdocs#1399]
before quitting Magento, I just wanted to say how stupid are the people who worked on it. do you even know the frustration people have to go through with the stupid readiness checks and all and just doesn't resolve????

try emulating word press than continuing with this f**ing stupid software.

**Comment by HeliumRaccoon** [comment]
there are plenty of option available it good to try another rather running after magentoo

**Comment by YannisMarios** [comment]
Magento is a nightmare...for example...
"Param resource doesn't pass validation: 'xxx_ccc_aaa::menuitem' does not match against pattern '\/^[A-Z][A-Za-z0-9]+_[A-Z][A-Za-z0-9]+::[A-Za-z_0-9]+$

An because of this in my module...Admin area is not reachable....

I wonder if people who wrote this were serious.
