### ISSUE TITLE
Backporting policy for security fixes should be included in the 2.2.0 change log

### ISSUE THREAD

**Issue by ekuusela** [magento/devdocs#1428]
Feedback on page: /guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html

As 2.2.0 contains backward incompatible changes and security fixes, will the security fixes be backported to 2.1.x?

**Comment by jfrontain** [comment]
good question, @ekuusela. Let me hunt down and answer, and then I'll edit the release notes accordingly. It might take a few days.

**Comment by piotrekkaminski** [comment]
@ekuusela couple things here:
-- all exploitable security issues fixed in 2.2 were also released in 2.1.9/2.0.16 recently. 
-- there are some security improvements in 2.2 like unserialize removal that are backward incompatible and will not be ported. However if there is/was a known exploit vector using them, it would be fixed or was fixed in a security patch for 2.1.x/2.0.x.

**Comment by jfrontain** [comment]
Hi @ekuusela, I see that Piotr answered your question about 2.2.0. I wanted to add that we are adding a note to the next set of release notes similar to the following note, and we'll continue adding this information to the release notes for all subsequent releases. Thanks again for this suggestion! 

"All exploitable security issues fixed in this release (2.2.6 ) have been back ported to 2.1.15 , 1.14.3.10, and 1.9.3.10. "
