### ISSUE TITLE
Build System Setup problem with DB. Magento 2.2.0

### ISSUE THREAD

**Issue by bmxmale** [magento/devdocs#1436]
Hello.

I go ahead of docs [build system setup] but when trying to `setup:di:compile` magento trying to connect to DB. Before I made `app:config:dump`. I think there is missing some step or similar.

 See my [question on stackexchange] for more details. An answer is provided on this page that may provide content towards writing/updating docs.

```
magento@578fc8d10f6d:/srv/magento2$ magento setup:di:compile


  [Zend_Db_Adapter_Exception]                                                                     
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  



  [PDOException]                                                                                  
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  



  [PDOException]                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known  


setup:di:compile
```

[question on stackexchange]: https://magento.stackexchange.com/questions/195295/magento-2-2-build-system
[build system setup]: http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/build-system.html

**Comment by lorikrell** [comment]
Revisiting and pulling together all issues for Pipeline deployment for devdoc updates.

**Comment by shrielenee** [comment]
Thanks @lorikrell! Any news on this thus far? 😄

**Comment by shrielenee** [comment]
Hellooo @lorikrell - It looks like the linked StackExchange post may provide a useful answer. Any info on this? Thanks!

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests).

We are closing this issue at this time.
