### ISSUE TITLE
rabbitmq priority for messages in M2EE?

### ISSUE THREAD

**Issue by valugi** [magento/devdocs#1441]
Hi,
I am curious if we can use different priorities for queue messages while using RabbitMQ in M2EE. I have seen no mentions of it so far, but maybe I was not looking in the right place. This is the feature I am talking about, it is implemented in the amq protocol and in the php library that M2 uses:

https://www.rabbitmq.com/priority.html
https://github.com/php-amqplib/php-amqplib/blob/5e8d3ace9af969c37877a2f4e7a0174b63736a59/PhpAmqpLib/Message/AMQPMessage.php

**Comment by shrielenee** [comment]
Hello @valugi and @keharper - It doesn't look we've had any traction on this. Due to inactivity, we are closing this issue. If you have further comments and feedback, or if you have updates @keharper, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
