### ISSUE TITLE
Ui Components linking: 'listens' paragraph incorrect

### ISSUE THREAD

**Issue by milansimek** [magento/devdocs#1451]
The 'listens' paragraph on the following page seems to be incorrect:

http://devdocs.magento.com/guides/v2.2/ui_comp_guide/concepts/ui_comp_linking_concept.html

The following file gives a clear example of how 'listens' works:

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/adminhtml/web/js/components/attributes-fieldset.js

**Comment by bdenham** [comment]
Hi @milansimek. Thanks for the info. We will be updating several parts of the UI components guide in the coming weeks and this issue will be a part of those updates. Thanks, again, for the link.

**Comment by shrielenee** [comment]
I have added this issue to our UI components work planning documentation for us to address in the scope of components work. Thanks!

**Comment by shrielenee** [comment]
@bdenham Hey Bruce -- is there an update on this? Is this a quick fix that we can accomplish before revisiting whole page changes in the future? Let us know! Thanks.

**Comment by lorikrell** [comment]
This issue may be related to this issue: https://github.com/magento/devdocs/issues/2078

**Comment by shrielenee** [comment]
Hello! We are archiving this ticket. Our Magento Community and Core developers and writers haven't had the bandwidth for an extended period of time to address this. We're archiving this in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily. 

This issue is related to a newer issue, https://github.com/magento/devdocs/issues/2078, which we are tracking.
