### ISSUE TITLE
Clean static files is not an option

### ISSUE THREAD

**Issue by KarlComSe** [magento/devdocs#1482]
Feedback on page: /guides/v2.2/howdoi/clean_static_cache.html

It i mentioned that there is a clean static files option.  System > Tools > Cache Management and click Flush Static Files Cache, is not available at least when in production mode.

**Comment by jeff-matthews** [comment]
@KarlComSe: Good catch. You're absolutely right. The **Flush Static Files Cache** is only available in `developer` mode. I suspect it's because in `production` mode, Magento doesn't generate or cache static files, therefore, there's no cache to flush. This [topic](http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-static-view.html#config-cli-static-overview) provides a better explanation.

I think a note or _(`developer` mode only)_ text beside the first option clarifying that it's only available in `developer` mode is the solution here. Let me know if you have any suggestions.

**Comment by korostii** [comment]
> I suspect it's because in production mode, Magento doesn't generate or cache static files, therefore, there's no cache to flush

Well, it does generate them, but that generation is invoked via an explicit CLI command `magento setup:static-content:deploy` only. 
Thus, flushing these files in `production` mode might turn your Magento instance unusable (unlike `developer` mode which would re-create these files on-the-fly when they are being requested from the server) until you run that command again.

**Comment by jeff-matthews** [comment]
That's correct. I meant to say that Magento doesn't auto generate static
files in production mode.
