### ISSUE TITLE
Move "First steps" to spoiler via details and summary tags

### ISSUE THREAD

**Issue by likemusic** [magento/devdocs#1490]
Many files in "Configuration guide" starts from "First step" block which takes up a whole page. It's very annoying to scroll every page to find where this block ends to start reading what you a really want.

What about move this block to spoiler by wrapping it with details and summary html tags?

**Comment by jeff-matthews** [comment]
@likemusic: You've raised a good point. I don't think that the "First steps" section is necessary in every topic, but instead of using a collapsible element I'd rather replace the section with one or two sentences about the Magento file system owner and link back to the [parent topic](http://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli.html#config-install-cli-first) for more information. What do you think?

**Comment by likemusic** [comment]
@jeff-matthews It would be great too :)

**Comment by jeff-matthews** [comment]
Changes are now live
