### ISSUE TITLE
Add the recommended value for php.ini variable `max_input_vars`

### ISSUE THREAD

**Issue by korostii** [magento/devdocs#1527]
Feedback on page: /guides/v2.1/install-gde/prereq/php-settings.html

Please see https://github.com/magento/magento2/issues/9317#issuecomment-341350686

Apparently, according to what seems to be an official response from the Community Engineering Team, it's a "correct Magento behavior" to have over 1000 html inputs on the product edit page in admin. Unfortunately, this behavior leads to an obscure error when using default PHP settings.

Please provide the recommended value for this `max_input_vars` variable in the docs (wherever appropriate and possible) so that this setting could be preset during Magento installation, in order to avoid the error mentioned above.

Thanks in advance & have a nice day!

**Comment by hostep** [comment]
I don't agree with this request. There is no recommended value, as its value can be custom to a certain project. In some projects the variable can stay on the default value, but for others, it might need to be increased.

Although it might be a good idea to add this to some kind of general troubleshooting page.

(Be aware that the `max_input_vars` variable was introduced in PHP 5.3.9 to prevent [DOS attacks](https://nikic.github.io/2011/12/28/Supercolliding-a-PHP-array.html), so please don't put the variable value too high in your projects.)

**Comment by korostii** [comment]
Well, personally, I'd rather see the originally bug fixed https://github.com/magento/magento2/issues/9317
It should be quite straightforward to serialize alll these inputs into a single JSON and send it via AJAX.

But, since apparently that's not gonna happen, IMHO some kind of warning in devdocs would seem appropriate. 

You're right, of course, that no specific constant value can safely fit all the projects.
Regardless, I'd be happy to see some kind of explicit official recommendation from @magento-engcom-team or @magento-team or whoever else regarding how to overcome this issue.

**Comment by jeff-matthews** [comment]
I don't think this is a documentation issue, especially since logging tells you what you need to know. There are lots of `php.ini` settings that could potentially affect a Magento installation, but we can't cover them all. 

@korostii, if you want to create a PR to add a note to this page, I'll reopen this issue and take a look.

**Comment by korostii** [comment]
> I don't think this is a documentation issue

I can not judge whether it's a documentation issue or a core bug.
But, with all due respect, it's a real issue I've seen merchants (repeatedly) run into.

> logging tells you what you need to know

That is if you even notice the issue in the first place. In the original bug report ( https://github.com/magento/magento2/issues/9317 ) you can see that there's no error message shown in admin.

> There are lots of php.ini settings that could potentially affect a Magento installation, but we can't cover them all

Respectfully, I don't see why not. After all, it's a finite number of settings.
If you don't like them shown on the documentation page, you could add them elsewhere (for example, updates the [sample php.ini file](https://github.com/magento/magento2/blob/2.2-develop/php.ini.sample) distributed with Magento) and then simply reference that external resource from the documentation page.


With that being said, I think personally I'd rather prefer seeing a resolution like "there is no official recommended value for this setting whatsoever" if that's really the case (especially considering the comment by @hostep).

In any case, thanks you so much for your attention and the precious time spent.
Keep up the good work & have a nice day!

**Comment by hostep** [comment]
Adding something like this to a troubleshooting page would be a good idea, but the problem is how would you describe something like this?
If the value isn't high enough, and you have a very big form with lots of input fields then you're going to trigger it, but such a form can appear everywhere, in the adminhtml, in the frontend, wherever someone decides to put such a field, it's a general PHP problem, not only Magento runs against this, so how should we describe such a problem? For as far as I know, this problem will only be logged and not being displayed on the frontend, so how can one identify this problem by only looking at his/her browser?

@korostii: do you have a suggestion for trying to describe this problem so it can potentially be added to a troubleshooting page in the documentation?

Maybe:
> If you have a form with lots of input fields, and submitting that particular form doesn't seem to work properly, you should consider increasing the php configuration `max_input_vars` to a higher number. This can happen in the adminhtml of Magento when you have a lot of storeviews and/or a lot of product attributes and/or attributes with a lot of options, ...

Something like this?
