### ISSUE TITLE
Too little information

### ISSUE THREAD

**Issue by Volvoxpl** [magento/devdocs#1629]
Feedback on page: /guides/v2.1/howdoi/checkout/checkout_order.html

Without information about how to add any description to validation and/or way to read information from checkout (to know what is state of other user selected fields) this description for validators is really not much use.

**Comment by jeff-matthews** [comment]
@dshevtsov, can you ask someone on Sustaining Engineering about this?

**Comment by aakimov** [comment]
@Volvoxpl 
Hi Misiu,
Thank you for your feedback. Unfortunately there is no unified way to describe all possible use cases that can involve additional validation on the payment step of the checkout.
In most cases additional validation means that the extension developer has added some custom control elements and wants them to be checked before the payment step is complete. We cannot predict how the state of this elements are stored and accessed or how the validation messages should be displayed for such components. That is why we cannot add it to this document.
However, if you want to see a real example of additional validation you can refer to CheckoutAgreements module (see app/code/Magento/CheckoutAgreements/view/frontend/web/js/model/agreement-validator.js). This module uses Magento native validation to check if user accepted agreements.
Speaking about accessing checkout state, you can inject 'Magento_Checkout/js/model/quote' in order to get the current state of the checkout process.
Thank you once again for the feedback.

**Comment by jcalcaben** [comment]
This issue has been addressed.
