### ISSUE TITLE
What it means?

### ISSUE THREAD

**Issue by SunshineTech** [magento/devdocs#1644]
Feedback on page: /guides/v2.2/extension-dev-guide/code-generation.html

Why should you regenerate code?

Suppose a Customer or Proxy class for a Customer class is generated and the Customer class has new methods added to it. 

There are two "Customer". What "a Customer class for a Customer class" means?

**Comment by jcalcaben** [comment]
Hi @SunshineTech I think you may have misread that statement, the docs say:

> Suppose a Factory or Proxy class for a Customer class is generated and the Customer class has new methods added to it.

So the paragraph is talking about a Factory class or a Proxy class that is dependent on the class signature of the Customer class. When new functions are added to the Customer class, the Factory or Proxy classes need to be regenerated to incorporate the update.

**Comment by shrielenee** [comment]
We haven't heard from you regarding this issue in two weeks. Due to inactivity, and our message explaining what you may have misconstrued, we are closing this issue. If you have further comments and feedback, please create a new issue. Thanks for taking the time to create a GitHub issue for docs improvement!
