### ISSUE TITLE
"Object that cannot be instantiated by the object manager."

### ISSUE THREAD

**Issue by bluk** [magento/devdocs#168]
On the [Dependency Injection](http://devdocs.magento.com/guides/v1.0/config-guide/config/depend-inj.html) page, there is a section that says:

"Object that cannot be instantiated by the object manager."

Technically there is nothing in the code that prevents this. (e.g. You can instantiate some of the named types using the object manager). There are many reasons why you shouldn't (which are explained correctly on the page) but I wouldn't call them "non-injectable". I would try to expand on what the differences are between "injectable" and "non-injectable" because from the text, I wouldn't know when to use factories and when to use the type as a singleton itself.

**Comment by antonkril** [comment]
Injectables can be instantiated by object manager without additional request-specific input: When you ask for eventManger, ObjectManager knows which specifically event manager you want, because there is only one event manager.

Non injectables can not be instantiated without additional input. 

When you ask for a product, ObjectManager does not know which specifically product you want, you have to either provide product id, or explicitly say that you want new empty instance of product. There is no way to provide product id in constructor signature, so product must not be asked in constructor.

**Comment by jcalcaben** [comment]
Content has been clarified. Please check the [dependency injection](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html) page and close this issue if it looks ok.

**Comment by bluk** [comment]
@jcalcaben I assume most of the content update was in https://github.com/magento/devdocs/commit/7f046d104d6047936483e6941346ea5331c8d4a1 . It looks consistent with the rest of the terminology. I did notice the model linked is incorrect (User vs. Product), but this seems outside this issue so will close.

```
[`app/code/Magento/User/Model/User.php`]({{ site.mage2000url }}app/code/Magento/Catalog/Model/Product.php){:target="_blank"}
```
