### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by clementblanco** [magento/devdocs#1695]
Feedback on page: /guides/v2.2/extension-dev-guide/build/module-file-structure.html

Sorry but this whole documentation for PHP developers looking to "use Magento 2.2+ as a real solid framework to develop additional functionalities into as Modules" doesn't seem to be as organised, as clear, as well written as what I'm used to use: 
https://laravel.com/docs/5.5.

Even [those blog posts](https://alanstorm.com/category/magento-2) look better and make more sense for PHP developers.

I'm looking to understand the base principles around the core of the framework, things like Models and Resource Models... CRUD, Controllers... like you can find in the "The Basics" section on Laravel documentation but can't find much relevancy.

Also a shame that it seems you have to use some kind of un-official third party tools like [pestle](https://github.com/astorm/pestle) or [magento2-configurator](https://github.com/ctidigital/magento2-configurator) for things we could expect to be available out of the box.

I know it's easier to complain rather than actively do something to improve things but I guess I was expecting more from the **official documentation**.

**Comment by jeff-matthews** [comment]
@Claymm, I'm sorry to hear that you haven't had a good experience with the Magento developer documentation. The documentation team at Magento is constantly looking for ways to improve the docs and community feedback is critical to our success. Would you be willing to help us identify _specific_ things we can do to improve the content? Would you be willing to contribute?

It sounds like you're having trouble finding information about "..base principles around the core of the framework..." Have you reviewed the [Architecture Guide](http://devdocs.magento.com/guides/v2.2/architecture/bk-architecture.html)? I think you'll find what you're looking for there, but let me know if not.

As for third-party tools, I encourage you to start a conversation about that on another forum (e.g., [Magento Stackexchange](https://magento.stackexchange.com/), [magento/magento2](https://github.com/magento/magento2/issues) repo) since that's less of a documentation concern and more of an engineering/implementation concern.

**Comment by jeff-matthews** [comment]
We'll add this to a list of community contribution projects for 2018. Thanks for the feedback!
