### ISSUE TITLE
This changelog is not accurate to what is actually in the version

### ISSUE THREAD

**Issue by SpencerRohan** [magento/devdocs#1746]
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.11EE.html

There is evidence to believe a push to v2.1.11 in the EE version(have not checked CE) that was not planned and not documented.   This version actually does not work as expected now.

Many vendor files were altered in the foundation.  First found evidence of this in the Magento  Sales module,  Magento\Sales\Model\Order\Payment\State\CaptureCommand.  

It's now unexpectedly giving a `"Fatal Error: 'Uncaught Error: Call to a member function getOrderStatusByState() on null in /var/www/magento/vendor/magento/module-sales/Model/Order/Payment/State/CaptureCommand.php:54` 

Upon further examination it seems as if a good majority of the code base has been altered unexpectedly.  This happened within the last 20 days or so.

**Comment by scottsb** [comment]
Are you using a ParadoxLabs payment module by any chance? There is an issue magento/magento2#13583 that seems to tie back to that.

**Comment by SpencerRohan** [comment]
@scottsb We are working with ParadoxLabs, so that issue may highlight why that bug is occurring.  What this doesn't explain is why 2.1.11 was working and stable for us for months and without doing any sort of composer update -- 2.1.10 and 2.1.11's codebase changed to include this, and made our codebase unstable.  It didn't have this code roughly 20 days prior to this ticket creation.  The point of versioning is to avoid this sort of action.  If one wants/needs the update, the action to follow is to move to the newer version.  We believe someone merged code into 2.1.10 and 2.1.11 accidentally.

**Comment by SpencerRohan** [comment]
We had to move to 2.1.9 in order to create a stable environment -- for those who stumble on here

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
