### ISSUE TITLE
Video tutorials in documentation - mixed content error for youtube iframe

### ISSUE THREAD

**Issue by gaetanzip** [magento/devdocs#1815]
Feedback on page: /videos/fundamentals/add-a-new-table-to-database/

Hi,

All tutorial YouTube iFrames trigger a mixed-content error as they're loading a page with `http` protocol instead of `https`.

Thanks !

**Comment by jeff-matthews** [comment]
Thanks for letting us know @gaetanzip! We're looking for any other examples of mixed content errors, so please let us know if you discover any more. The fix for this particular issue should resolve all mixed content errors related to video tutorials. 

@belbiy, please link to the PR from the theme repo so we have a record of the change.
