### ISSUE TITLE
Add canonical URLs to all older versions of the same page.

### ISSUE THREAD

**Issue by paales** [magento/devdocs#1849]
I often encounter URL's in Google that direct to an old URL.

For example, when I google on 'magento 2.3 installation composer', the first hit is http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_composer.html

Now, the 2.0 documentation is out of date for most intents and purposes, so it would be great if Google would point to the 2.2 documentation (and move to 2.3 after its release).

To achieve this you can add a canonical meta tag, so that Google knows that the 2.0 page isn't the canonical source any more. This also increases ranking as all the 'SEO juice' goes to the latest version, improving ranking if multiple version score for that page. Also it will prevent duplicate-content penalties by Google.

**Comment by jeff-matthews** [comment]
Thanks for the feedback @paales! Every page currently contains a canonical URL. We use liquid templating in the `_includes.header.html` file like so:

><link rel="canonical" href="{{ page.url | replace:'index.html','' | prepend: site.baseurl | prepend: site.url }}">

What you seem to be suggesting is that we hard code all 2.0 canonical links to the latest version (2.2), but that may be problematic when 2.2 is no longer the latest version. Perhpas we need to revisit how we're building canonical links so that we're always building links with the latest version.

**Comment by paales** [comment]
If 2.2 isn't the canonical URL anymore, all the URL's need to change to 2.3, 2.4, etc. If that requires some refactoring, that is fine by me 😛.

**Comment by jeff-matthews** [comment]
This may not be a trivial change since we're using the `page.baseurl` variable to retrieve the file path, which includes the version number. I'm not sure how we would separate the version number from the path. We've updated our `robots.txt` file to stop indexing 2.0 files, which should help with issues like this in the future.

**Comment by paales** [comment]
@jeff-matthews That seems like a very bad Idea as you need to rebuild your ranking each time a new version is released.

**Comment by jeff-matthews** [comment]
That's a good point. We'll do some more research to see what options we have. 

@belbiy, do you have any thoughts?

**Comment by jeff-matthews** [comment]
I discussed this with the doc team and we came up with a good solution I think. 

First of all, we stopped noindexing the 2.0 directory.

Second, we're planning to change the project architecture and branching workflow to remove the version number from the URL of the _latest_ version of a topic. When you select an _earlier_ version of a topic, that URL _will_ contain the version number, but the canonical link for that version will point to the latest version. This will prevent canonical links from pointing to old versions and confusing search engines.

**Comment by jeff-matthews** [comment]
We've just finished scoping and planning the internal project that will solve this issue. Will update when more info is available, but we expect to complete this by the end of the year.

**Comment by jeff-matthews** [comment]
PR https://github.com/magento/devdocs/pull/3462 will use the latest version for canonical URLs. When we implement our new branch versioning project, we'll revisit this as needed. In the meantime, this, along with the new sitemap.xml file should mitigate these SEO issues.

**Comment by jeff-matthews** [comment]
This PR is also related https://github.com/magento/devdocs/pull/3463.
