### ISSUE TITLE
Not able to edit Conditional Payment methods

### ISSUE THREAD

**Issue by hassanshuja** [magento/devdocs#1932]
![image](https://user-images.githubusercontent.com/5621020/40274209-227f5d58-5bea-11e8-8a3b-2868a1924016.png)

I have an issue that i have two payment method one is for subscription subscribe_pro extension and other is without subscription that is ebizcharge_ebizcharge extension. But I want to hide ebizcharge_ebizcharge payment method when subscription product selected. where can I edit the code for payment methods to make it conditional? I have not found a solution . can you please guide me

**Comment by hostep** [comment]
Since you mentioned in https://github.com/magento/magento2/issues/15388 that you resolved the issue, this ticket can get closed as well I suppose?

But feel free to update with how you've resolved it.

Next time when you have a question about how to use Magento, you can go to:
https://community.magento.com/ or https://magento.stackexchange.com/
Github's purpose is meant for reporting bugs, not for asking questions about how to use the software ;)

Thanks!

**Comment by jeff-matthews** [comment]
Thanks @hostep!
