### ISSUE TITLE
Magento 2 (Version 2.2.3) Advanced Reporting Not Working

### ISSUE THREAD

**Issue by iindranil** [magento/devdocs#2092]
Having the 404 error page after successfully configured all the setting as per the documentation. Can you guys please advice what I am missing ? Thank you,

![configuration settings stores magento admin 7](https://user-images.githubusercontent.com/39942912/40961245-abfe98d2-68bf-11e8-967e-7d76ff6c6b63.png)

![integrations extensions system magento admin](https://user-images.githubusercontent.com/39942912/40961368-ffbcc246-68bf-11e8-99f4-9b4b56bdfa99.png)

![34986916-ac396d78-fab9-11e7-9fa2-c006d39619b8](https://user-images.githubusercontent.com/39942912/40961303-ccd7d0d2-68bf-11e8-8208-cf7ac7860796.png)

**Comment by jeff-matthews** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://magento.stackexchange.com/). To report Magento 2 code issues, see the [Magento 2 GitHub repo](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by iindranil** [comment]
Any update on this ?
