### ISSUE TITLE
Feedback on page: /guides/v2.2/mtf/mtf_introduction.html

### ISSUE THREAD

**Issue by OccamsRazorCoder** [magento/devdocs#2209]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [X ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:

  How about saying where you need to install the test framework.  Does it need to be installed on the Magento Server or can it be installed on a Desktop PC Connected to the internet?      Have a diagram showing configurations.    Also a brief overview of what it can do.   Can the testing framework randomize cart selections over the entire inventory.    So you can setup a system of concurrent users to be able to add a maximum number of items from the inventory until the entire inventory is selected and tested?     

### Steps to reproduce

Just go to first page. 
1. First Step
2. Second Step
3. Etc.

**Comment by shrielenee** [comment]
Hey @dshevtsov - Have you had any chance to review this? Let us know so we can update the issue. 👍

**Comment by shrielenee** [comment]
Hello there @OccamsRazorCoder! We have moved on to the new and improved [MFTF](https://devdocs.magento.com/mftf/2.2/introduction.html), and while we are still maintaining MTF any new efforts are relegated to MFTF.

Due to bandwidth concerns, @dshevtsov and I will be closing this issue so we can focus keenly on MFTF updates and improvements. Thanks for bringing this to our attention!
