### ISSUE TITLE
Community input: Extension developers

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/devdocs#224]
The following topics in the Extension Developer Guide are up for grabs. If you have input, click **Edit this page on GitHub** on any of the topics:

*    <a href="http://devdocs.magento.com/guides/v1.0/extension-dev-guide/template_create_req_config_files.html">Create the required config files</a>

*    <a href="http://devdocs.magento.com/guides/v1.0/extension-dev-guide/template_package_module.html">Package a module</a>

*    <a href="http://devdocs.magento.com/guides/v1.0/extension-dev-guide/template_verify_new_module.html">Verify the new module</a>

**Comment by tiwarimukesh** [comment]
package a module and verify new module redirects us to 404 page.

**Comment by tanberry** [comment]
Sorry about that, @tiwarimukesh! We will review and probably close this issue, because we did finally manage to write at least basic topics on these three topics.

But in the meantime... if you can add any content or have any edits/comments on the page that we did finally write about verifying a new module, it would be great! It's here, feel free to do a PR or open an Issue: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/validate/test-module.html

Really, feel free to edit/contribute to any topics at all that you have special knowledge/interest. Thanks!

**Comment by tanberry** [comment]
Oh, and the current topic about packaging a module is here: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/package/package.html
;-)

**Comment by xcomSteveJohnson** [comment]
@tiwarimukesh Can we close this?

**Comment by tiwarimukesh** [comment]
@xcomSteveJohnson Yes you can close this.

**Comment by xcomSteveJohnson** [comment]
Closing
