### ISSUE TITLE
Why Magento 2.2.3 doesn't support on save indexing while mass updating products?

### ISSUE THREAD

**Issue by ssaurabh** [magento/devdocs#2263]
## This issue is a:
- [x] Bug on the website
- [x] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

**Comment by ssaurabh** [comment]
As we all know Magento 2.X.X supports indexing on **saving** and on **schedule**. 
However, I found it is working only for single product update, Magento2.2.3 doesn't work with on **MASS** products update. 
I think that is a bug in Magento 2.x.x it should create the index on MASS update/save also.

**Comment by jeff-matthews** [comment]
Hi @ssaurabh,

Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
