### ISSUE TITLE
METODOS DE PAGO PAYPAL MAGENTO

### ISSUE THREAD

**Issue by Andreavbr** [magento/devdocs#2544]
Estoy intentando realizar una apps con magento y la estoy tratando de configurar con paypal pero debo de colocar el code de el, algo asi como lo que esta en rojo y no logro desifrar cual es? Estoy utilizando PayPal Express Checkout

**Comment by jeff-matthews** [comment]
hi @Andreavbr,

Since I'm not fluent in Spanish, I used Google Translate to translate your comment.

> I'm trying to make a apps with magento and I'm trying to set up with paypal but I must place the code of it, something like what is in red and I can not desifrar it is? I am using PayPal Express Checkout

Based on your feedback, it doesn't seem like your issue is related to Magento documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). 

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). 

Thanks for taking the time to create a GitHub issue for docs improvement!
