### ISSUE TITLE
Installation won't complete > fCGI conflict?

### ISSUE THREAD

**Issue by siniztr** [magento/devdocs#2581]
# Bug report

## Description

Installation script freezes after installing modules

### Steps to reproduce
Doing full install from package downloaded from magento.com (with samples) on Ubuntu server with PHP7.1 and FastCGI/HTTP2.

1. First Step  
Upload files via sFTP to server
2. Second Step
Do webinstall and create database using phpmyadmin. All modules enabled. 

## Expected result

Full and successful installation of Magento.

## Possible solutions

Error from Apache2 logfiles:

>  [proxy_fcgi:error] [pid 1547:tid 140267736053504] [client 84.245.15.8:51073] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Warning: ini_set(): Cannot find save handler 'db' in /var/www/youtube/magento/vendor/magento/framework/Session/SessionManager.php on line 563 in /var/www/youtube/magento/vendor/magento/framework/App/ErrorHandler.php:61\nStack trace:\n#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'ini_set(): Cann...', '/var/www/youtub...', 563, Array)\n#1 /var/www/youtube/magento/vendor/magento/framework/Session/SessionManager.php(563): ini_set('session.save_ha...', 'db')\n#2 /var/www/youtube/magento/vendor/magento/framework/Session/SessionManager.php(184): Magento\\Framework\\Session\\SessionManager->initIniOptions()\n#3 /var/www/youtube/magento/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(167): Magento\\Framework\\Session\\SessionManager->start()\n#4 /var/www/youtube/magento/vendor/magento/framework/Session/SessionManager.php(130): Magento\\Backend\\Model\\Auth\\Session\\Interceptor->start()\n#5 /var/www/youtube/magento/vendor/magento/module-b...\n', referer: **depreciated for privacy reasons**

## Additional information

Ubuntu 17.10 running Apache2, mySQL, http/2 and LetsEncrypt. 
Loaded PHP modules: 
apc, apcu, bcmath, calendar, Core, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring, mcrypt, memcache, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, readline, recode, Reflection, session, shmop, SimpleXML, soap, sockets, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter ,xsl ,Zend OPcache ,zip ,zlib

**Comment by jeff-matthews** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). 

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by siniztr** [comment]
Hmmm that's strange I thought I went to the Magento 2 GitHub. Apologies.
