### ISSUE TITLE
Feedback on page: /guides/v2.1/release-notes/ReleaseNotes2.1.4CE.html

### ISSUE THREAD

**Issue by mohitmehta1996** [magento/devdocs#2583]
# General issue
Issue in checkout for multiple address.

## Description:
If a customer has 3 address and if any of the address is not complete then magento does not let him checkout even though he has selected complete address for shipping & billing.

I have migrated from magento 1 to magento 2.1.4. So some customers have missing region or postcode. So it cause above issue.

**Comment by jeff-matthews** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). 

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
