### ISSUE TITLE
Feedback on page: /guides/v2.2/frontend-dev-guide/templates/template-walkthrough.html

### ISSUE THREAD

**Issue by ArmenBodour** [magento/devdocs#2721]
# General issue
Set your Magento application to the developer mode
## Description:

How do you do this, and why is it not shown?

## Possible solutions:

In order to change magento 2.0 mode you have to run this command php bin/magento deploy:mode:set developer in CMD or your SSH windows into magento 2.0 root folder. More information you can find here and here.

## Additional information:

Before submitting this issue, please make sure you are complying with our Code of Conduct:
https://github.com/magento/devdocs/blob/develop/.github/CODE_OF_CONDUCT.md

Issues that do not comply with our Code of Conduct or do not contain enough information may be closed at the maintainers' discretion.

**Comment by osrecio** [comment]
Hi @ArmenBodour In the page you have a link to [Set Mode](https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-mode.html)

In the word "Set" is a link to config cli command mode.

```
[Set]({{ page.baseurl }}/config-guide/cli/config-cli-subcommands-mode.html) your Magento application to the developer [mode]({{ page.baseurl }}/config-guide/bootstrap/magento-modes.html)
```

Raw: 
[Set](https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-mode.html) your Magento application to the developer [mode](https://devdocs.magento.com/guides/v2.2/config-guide/bootstrap/magento-modes.html)

I will close the ticket because the information is defined, feel free to reopen it.
