### ISSUE TITLE
Massive update of stock

### ISSUE THREAD

**Issue by CaronteVIII** [magento/devdocs#2780]
Is there any way to massively update the stock of a set of items without having to update one by one?
Thanks!

**Comment by CaronteVIII** [comment]
For Magento 1.9

**Comment by jeff-matthews** [comment]
Thank you for your feedback! However, it doesn't appear that your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). 

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
