### ISSUE TITLE
Speed up chmod commands

### ISSUE THREAD

**Issue by springimport** [magento/devdocs#3024]
# General issue
[Settings permissions](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html) is too slow.
```
cd <your Magento install dir>
find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;
find var vendor generated pub/static pub/media app/etc -type d -exec chmod u+w {} \;
chmod u+x bin/magento
```

## Description:
As is known, commands like find + chmod work not fast. Especially for huge systems like magento with big file base. I think we should to find how to speed up settings permissions.

## Possible solutions:
1. Is it necessary to set write permissions for vendor directory? I think no. Just remove `vendor` directory from path list. I don't think it requires w permission.
2. Use xargs.
Example:
```
cd <your Magento install dir>
find var vendor generated pub/static pub/media app/etc -type f -print0 | xargs -0 chmod u+w
find var vendor generated pub/static pub/media app/etc -type d -print0 | xargs -0 chmod u+w
chmod u+x bin/magento
```

**Comment by hostep** [comment]
I agree with @springimport that running `-exec some-cmd {} \;` is many times slower then `-print0 | xargs -0 some-cmd`, but while [researching a bit more](https://www.everythingcli.org/find-exec-vs-find-xargs/), it looks like the `-exec` flag has a better, more performant implementation if you let it end with `+` instead of `\;`, as long as the command is able to deal with multiple arguments,  so something like this runs with the same speed as the `xargs` solution:

```
cd <your Magento install dir>
find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} +
find var vendor generated pub/static pub/media app/etc -type d -exec chmod u+w {} +
chmod u+x bin/magento
```

Is this considered a better solution then the `xargs` solution? I don't know? According to [this article](https://www.everythingcli.org/find-exec-vs-find-xargs/): `xargs` splits everything in batches of 5000 items, while `find -exec` would run it over all found files. I seem to remember that there is some kind of limit where if you want to run a command with a huge number of arguments that the shell will start complaining. So maybe the `xargs` solution is more capable of dealing with such things.

A downside of `xargs`, is that if the find command finds zero files, `xargs` will fail with certain commands, unless you add the `--no-run-if-empty` flag. Which only seems to work on Linux, macOS doesn't have this flag.

Not sure what the best solution would be here?
I'm in favour of changing the `\;` with `+` since the diff will be less complex to review (at least 28 files in the devdocs repository would need to be updated)

And finally some benchmarks on a vanilla Magento 2.2.6 installation, running on a very speedy SSD:
```
$ time find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;

real	2m14.465s
user	0m46.937s
sys	1m7.681s

$ time find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} +

real	0m0.889s
user	0m0.210s
sys	0m0.665s

$ time find var generated vendor pub/static pub/media app/etc -type f -print0 | xargs -0 chmod u+w

real	0m0.677s
user	0m0.347s
sys	0m0.653s
```

As for:
> Is it necessary to set write permissions for vendor directory? I think no. Just remove vendor directory from path list. I don't think it requires w permission.

I think Magento has some sort of wizard in the backend which can also deal with composer updates (never used it myself though), so php would also need write permissions for this to work I assume.

**Comment by jeff-matthews** [comment]
Thanks for the thorough research @hostep!

**Comment by springimport** [comment]
@hostep I've applied this new solution for my deployment process and reduced the build time by 30%: from 3 to 2 minutes. Thanks!

**Comment by hostep** [comment]
Nice!
