### ISSUE TITLE
The <action> instruction is deprecated

### ISSUE THREAD

**Issue by neirda** [magento/devdocs#310]
There is an alert saying "The &lt;action&gt; instruction is deprecated. Do not use it." on the layout XML instructions page:
http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_act

Why is that and is it possible to accomplish that another way?

I found another use example on this page:
http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/layouts/xml-manage.html#layout_markup_block-properties

**Comment by almarchenko** [comment]
Thanks for the comment!
We'll be back with the reply soon.

**Comment by almarchenko** [comment]
Hi again!
>Why is that and is it possible to accomplish that another way?
The <action> directive is marked as deprecated because we want to stop using imperative directives and switch to using declarative layout directives instead. 
The recommended way to avoid <action> is using <block><argument></argument></block> construction (will make it more clear in the doc).
But, the refactoring is still in progress, and some block methods can still be called only using <action>.
This is why we have described. 
@neirda please let us know this answers your question.

**Comment by neirda** [comment]
Ok thanks for the explanation
