### ISSUE TITLE
Build using Docker is missing docker-compose.yml

### ISSUE THREAD

**Issue by Delyman** [magento/devdocs#3351]
# Bug report

## Description

When I use Docker to build the devdocs,it do not work. The ERROR prompt message is "Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml"
### Steps to reproduce

1. install the Docker in windows10 pro 
2. Download ZIP (under the "clone or download",I Just download the zip(devdocs-master.zip))
3. Unzip the devdocs-master.zip in Newfolder and rename the Newfolder to "devdocs"
4. Use the terminal to navigate to the "devdocs" directory.
5.Run docker-compose up to initialize the build process. 

## Expected result

Is the docker-compose.yml missing or ? How can I get the docker-compose.yml ?

**Comment by Delyman** [comment]
Anyone can tell me why "Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml"

**Comment by jeff-matthews** [comment]
@Delyman, I'm not familiar with our Docker implementation, but I'll see what I can do to help.
 
The only `docker-compose.yml` that I'm familiar with was added by one of our DevOps people to facilitate a CICD process. Here's the commit: https://github.com/magento/devdocs/commit/547f09d4f29793be50f8a92b1c90a25f40d7cce2.

This CICD process was abandoned, so we did some cleanup and removed both the `Dockerfile` and `docker-compose.yml` files from the repo.

Since I'm pretty sure that our Docker implementation for simply building devdocs locally was implemented prior to that DevOps commit, I'm not sure how it's supposed to work (e.g., do we need to restore the `docker-compose.yml` DevOps file?).

@jcalcaben, can you confirm?

**Comment by jcalcaben** [comment]
@jeff-matthews correct. We no longer maintain a docker file in the project. 

We need to update the README file to remove the section about using docker or restore that file and test it to make sure it still works.

**Comment by Delyman** [comment]
@jeff-matthews @jcalcaben Thank you for telling me about the  issue! When the README.md file updated, I will try the other way.
