### ISSUE TITLE
Redis - Suggestions on improving the documentation

### ISSUE THREAD

**Issue by aoldoni** [magento/devdocs#343]
Hi,

For the page: http://devdocs.magento.com/guides/v2.0/config-guide/redis/config-redis.html - I suggest we make the documentation more self-contained.

By this I mean, there are lots of links in the documentation of information that I believe should really be in the documentation itself.

Some examples are:
- The ECG PDF information about: Redis settings, information on how to calculate some of the Redis settings (like memory limit), cleaning old tags script (is it available for M2?), etc. This should be added to the documentation.
- From the digital ocean link: how to install Redis.
- From the further external links: installation procedure, command line usage, etc.
- Impacts of catalogue size (or other information) into the amount of memory used by Redis, etc.
- etc.

The external links for blog posts might not be available some time in the near future so I guess a more stand-alone communication is preferable. Links to official documentation are more reliable though.

Thanks!

**Comment by xcomSteveJohnson** [comment]
It's always dicey to document installing third-party programs and because Redis isn't mandatory, and because we assume some level of sophistication for anyone who would deploy Redis, I'm not in favor of documenting the installation steps. (Time is also an issue.)

ECG wrote about Redis for Magento 1.x. I'll check with them to see if it's applicable to Magento 2.

The other things you mention are good, we'll see how it goes. (Time is definitely an issue.)

**Comment by xcomSteveJohnson** [comment]
@aoldoni Update. Short term, I can answer most of your questions except the ECG ones. After consulting them, it appears that a lot of the information in that Expert paper isn't applicable so I'll remove the link.

Look for an update in the next week. Thanks for the suggestions!

**Comment by aoldoni** [comment]
Thanks, I will continue checking.

**Comment by xcomSteveJohnson** [comment]
Short update. As for installation, I'm open to that; however, we recently discovered that Redis isn't practical to use for session storage because we don't do locking with it. Time permitting I'll set it up for caching and add install instrux with links to the Redis site.

Found out that ECG's Redis documentation applies to Magento 1.x only but I'll ping them for an update soon.

**Comment by xcomSteveJohnson** [comment]
@aoldoni Is it fair to say that this request is to include installation information? Anything else?

Redis can be used for session storage in Magento 2.1 so we'll have some more updates then.

Created internal issue MAGEDOC-2501 to track.

**Comment by aoldoni** [comment]
Hi @xcomSteveJohnson - I believe installation information can be referred to the official installation guide (currently already linked).

**Comment by xcomSteveJohnson** [comment]
Can we close this?

**Comment by xcomSteveJohnson** [comment]
Closing. Please reopen if you need other things changed.
