### ISSUE TITLE
Add 'current page' highlight + breadcrumb

### ISSUE THREAD

**Issue by paales** [magento/devdocs#3885]
# New feature request

## Description

Requested something similar earlier in #793, but I think we got a miscommunication or something.

If you go to https://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html you have a nice subnavigation on on this page and are able to navigate to child-pages, this is good.

But you can't actually see that this page is beneath 'Development', there isn't anything highlighted in the header. I can't create a mental hierarchy of the devdocs website and feel lost on every page I visit, because I feel that I'm in special website dedicated to this section.

This happens because you usually get deeplinked to a page.

## Expected result

I want to know 'where' in the DevDocs website I am so I know it immediately when I visit from a deeplink.

## Benefits

You'd actually know where you are and get less overwhelmed by Magento. We need all the help we can get, you know :)

## Possible solutions

1. Highlight the Main Menu icon so it becomes clear that is part of that page.
2. Create some form of 'breadcrumb' above 'UI Components Guide'

**Comment by dobooth** [comment]
![navbar](https://user-images.githubusercontent.com/45772453/54368280-d7de4f00-4641-11e9-9859-1523ed648411.gif)

**Comment by dobooth** [comment]
@belbiy Seems like a good idea...

**Comment by jeff-matthews** [comment]
I just want to provide some background that we should consider when working on this. 

We used to have breadcrumbs at the top of every page on devdocs, but they were a little buggy and didn't work as expected in all scenarios.

Also, generating breadcrumbs accounted for an inordinately high percentage of build time (I don't recall the precise number). If we start exploring the use of breadcrumbs again, I want to make sure that they work correctly and that they don't increase build time by an unreasonable amount.

**Comment by shrielenee** [comment]
@belbiy What do you think about this idea? ❓

**Comment by belbiy** [comment]
This is awesome idea, highlighting the current top nav should improve the understanding of the navigation, especially in the inner pages. 

I have been researching this for a long time and have no idea how to implement it with our current nav system. 

We have 2 data sources to generate navigation: [_data/main-nav.yml](https://github.com/magento/devdocs/blob/master/_data/main-nav.yml) and [_data/toc](https://github.com/magento/devdocs/tree/master/_data/toc) files for each guide.

Somehow the top navigation needs to know what page in `_data/toc/*` belongs to what top level item in `_data/main-nav.yml`. 

I see 3 possible strategies:
1. Add some sort of a metadata to `main-nav.yml` that "connects" the top level items to our toc groups: 
```
- label: Setup
  groups: ['installation-guide', 'software-update-guide' , '..' ...etc]
  children:
``` 
2. Merge ALL the navigation files into one big tree, and use the tree structure as indicator of what top level item is the parent of the bottom-level.
3. Use some sort of clever url comparsion between the two navigations to determine the relationship. Possibly with JavaScript, because it will be very difficult to do in Jekyll. I do not recommend going with this approach, specially because our URL structure is not always consistent.

Does anybody have better ideas? Or maybe have time to work on either one option?

**Comment by jcalcaben** [comment]
@belbiy are there any updates on this issue?

**Comment by shrielenee** [comment]
@hguthrie is researching whether this is an internal issue and will update or close this as she sees fit! 🙇‍♀

**Comment by hguthrie** [comment]
Just to be clear, according to the original request, there is a perception that this guide is "beneath" or a part of an overarching development entity. The example provided is a topic in the UI Components guide. We use the Development drop-down navigation to categorize these guides as part of a Magento development stage of need. Structurally, they are not connected outside of the navigation. The problem here is that, despite the actual structure, readers need a point of reference.

I do agree that it is useful for the reader to know where they are in relation to the open guide and to select any topic along that navigation chain to open and review. But I also think there is a larger issue here regarding the stage of need: Install, Development, and Testing.

This requires a thoughtful review that involves all of DevDocs. Unfortunately, we cannot prioritize it at this time. I will leave this issue open because this is a valid concern. We are actively developing plans to improve the reader experience and the ideas noted here can help us to better support those plans.

**Comment by dobooth** [comment]
Closing this issue. Let's see what upcoming capabilities we will have.

**Comment by hguthrie** [comment]
@wsibennett  The documentation site has moved to [Adobe Experience League](https://developer.adobe.com/commerce/frontend-core/ui-components/).
