### ISSUE TITLE
FreshDesk / Magento 2 extension - missing dev doc

### ISSUE THREAD

**Issue by daolwede** [magento/devdocs#4571]
# New topic request

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains code samples that shows ____.
- [ ] Other (please specify)

**Comment by daolwede** [comment]
The following url: http://devdocs.magento.com/guides/v2.1//get-started/authentication/gs-authentication-token.html is listed within the installation information screen to find out about integration tokens. However the link is now a page not found...

**Comment by keharper** [comment]
@daolwede Where did you encounter that link? The problem is that there are two slashes (//) after `v2.1`. Remove one of them, and you'll get the topic you're looking for. 

Let us know where the broken link is. The broken link doesn't show up in our tests, so we'll try to determine why and fix any others like this.

**Comment by daolwede** [comment]
@keharper 

Thanks. I did not spot the // in the url and the link works as expected now. The incorrect link appears in the Freshdesk/Magento 2  installation instructions which I got to through my FreshDesk account. It can also be seen here: https://www.freshworks.com/apps/freshdesk/magento_2/ on the 'Instructions' tab (you'll also need to click the 'expand' link).
