### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html

### ISSUE THREAD

**Issue by luo3555** [magento/devdocs#4763]
In afterSave function, what's customDataRepository? where can I get it ?

**Comment by shrielenee** [comment]
Hello @luo3555 --- The`customDataRepository` is a custom repository that the user (you) would create. 

See this sentence in the page --- "In order to retrieve a product or a list of products from the Magento API, you need to make an API request to the appropriate service (the Product Repository in this case)."

It's a sample term/placeholder that you would replace with the name of your own custom repository.

I'm going to close this issue for now. If you have further questions please raise this issue in our Community Engineering Slack magentocommeng.slack.com!
