### ISSUE TITLE
Feedback on page: /extensions/amazon-sales/

### ISSUE THREAD

**Issue by juaniAla** [magento/devdocs#4788]
# General issue
Problems with the CPU usage of the php-fpm process when I install the Magento_ServiceConnector module
## Description:
To install the Amazon Sales Channel module, the Magento_ServiceConnector module in version 1.0.3 is required.
As soon as I install the latter, many php-fpm processes are created and I consume 100% of the CPU leaving the system almost unusable.
## Possible solutions:
Some have ideas that may be happening?

regards
thank you

**Comment by bdenham** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the Magento Support Knowledge Base, forums, or Stack Exchange. To report Magento 2 issues with code, see the Magento 2 GitHub. To suggest new product features and enhancements, see Magento features and improvements. Thanks for taking the time to create a GitHub issue for docs improvement!
