### ISSUE TITLE
Feedback on page: /guides/v2.3/rest/tutorials/orders/order-create-order.html

### ISSUE THREAD

**Issue by RajendraNayak** [magento/devdocs#4800]
# General issue

## Description:

According to document after consuming "carts/mine/payment-information" API, Sale Order status should be "Pending" but in my case it is showing as "Processing".

Below is the response i am getting in "order details" API along with other details
{
...
"state": "processing",
    "status": "processing",
....
}

## Possible solutions:
Order status should be "Pending" at this stage.

Order status should be "Pending" at this stage.

**Comment by keharper** [comment]
@RajendraNayak Did you use the `banktransfer` payment method? The status immediately after creating an order may vary, depending on the payment method.

If yes, I'll have to investigate whether the behavior changed for this payment method.

**Comment by RajendraNayak** [comment]
Thanks for your quick reply.
Yes i am using banktranfer payment method.
I am using CCAvenue {"method":"ccavenuepay"}.

**Comment by RajendraNayak** [comment]
> @RajendraNayak Did you use the `banktransfer` payment method? The status immediately after creating an order may vary, depending on the payment method.
> 
> If yes, I'll have to investigate whether the behavior changed for this payment method.

Thanks for your quick reply.
Yes i am using banktranfer payment method.
I am using CCAvenue {"method":"ccavenuepay"}.

**Comment by keharper** [comment]
@RajendraNayak If this is what your `paymentMethod` definition looks like

```
	"paymentMethod": {
    	    	"method": "ccavenuepay"
	 },
```

then the CC Avenue payment method is processing the transaction as a standard online payment processor. The tutorial uses an offline payment method, (`"method": "banktransfer"`) because it's built-in to Magento, and everyone can use it. 

I would expect a typical online payment method to have different `state` and `status` values than what's shown in the tutorial. The processor may have captured the funds immediately.

**Comment by RajendraNayak** [comment]
> @RajendraNayak If this is what your `paymentMethod` definition looks like
> 
> ```
> 	"paymentMethod": {
>     	    	"method": "ccavenuepay"
> 	 },
> ```
> 
> then the CC Avenue payment method is processing the transaction as a standard online payment processor. The tutorial uses an offline payment method, (`"method": "banktransfer"`) because it's built-in to Magento, and everyone can use it.
> 
> I would expect a typical online payment method to have different `state` and `status` values than what's shown in the tutorial. The processor may have captured the funds immediately.

@keharper 
But i never redirect to CCAvenue page. I am still on checkout page and on checkout page itself Sale Order status & state both are showing as "Processing" in database. Suppose user didn't pay then status remains processing which is wrong.

**Comment by keharper** [comment]
I can't be of any help here, because I don't have any knowledge of 3rd party payment methods. If you discover there's a missing step between 7 and 8 for online payment methods, please open a new issue, and we'll try to work it into the tutorial. Perhaps someone on the Community Engineering Slack channel or on Stack Exchange can answer your question.
