### ISSUE TITLE
Feedback on page: /guides/v2.3/extension-dev-guide/versioning/dependencies.html

### ISSUE THREAD

**Issue by victortodoran** [magento/devdocs#4881]
# General issue

## Question:

Why is it that when changing the **preference** of a **class** marked with `@api` you can depend on a **MAJOR** version but when you change the preference of an **interface** marked with `@api` you have to depend on a **MINOR** version release. Is it not kinda the same thing?

Same thing goes for implementing an **interface** (depend on **MINOR**) and **extending** a concrete **class** (depend on **MAJOR**) both marked with `@api`

Then if you look at **JS classes** marked with `@api` you must depend on a **MINOR** version when extending

What is the reasoning behind this? Are the docs wrong? 

IMHO implementing an interface should not make me more dependent of a module than extending a concrete class.

**Comment by buskamuza** [comment]
MAJOR version is used to mark API changes, MINOR version is used to mark SPI changes (see https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/dependencies.html#service-provider-interfaces)
It could be vice versa, and we would get similar questions, so it's just how it is declared.

Now,
* if you create a class that implements an API interface, your implementation will be broken if we add new method to the interface. We mark "adding a new method" as a MINOR change. That's why you should depend on MINOR version. If you declare preference for an interface, you probably implement it. That's why it's MINOR dependency.
* if you create a class that extends from an API class, your implementation won't be broken (most likely, there is still a possibility of conflicting names) if we add a method, so you don't need to depend on MINOR version. You should depend on MAJOR because we can remove the class completely (it's a MAJOR change). You might also be affected by a method removal (because you may call it from your child class), which is also a MAJOR change. If you redefine preference for a class, most likely you extend it. That's why the recommendation is MAJOR version dependency.

We're cleaning up JS section now, btw - https://github.com/magento/devdocs/pull/5096
