### ISSUE TITLE
Gift options location 

### ISSUE THREAD

**Issue by campan85** [magento/devdocs#5020]
# General issue

 wrong description of the Gif options location  
https://docs.magento.com/m2/ee/user_guide/sales/gift-options.html
Here is a sshot of the current Magento 2.3 documentation: https://prnt.sc/oiwf77

## Description:
It is written that the Gift options are located under Stores -> Configuration -> Sales -> Checkout -> My Cart link -> Gift options but there is only the Display cart summary options. 

## Possible solutions

Gift options are located under Stores -> Configuration -> Sales -> Sales. 
Here is a sshot of the current Magento 2.3.2 Commerce edition admin panel where the Gift options are located: https://prnt.sc/oiwfu9

**Comment by shrielenee** [comment]
Hello @campan85 --- Our merchant user guide docs are not yet open for open source contribution (though our DevDocs are), but they will be in the very near future! This issue you are reporting is applicable to merchant user guide docs.

I am closing this issue, but will raise it to the merchant docs team and @leslietilling in the meantime. If they want to add it to our internal backlog they can. Otherwise, keep your eyes peeled for a September date in which we will open merchant docs for contribution!
