### ISSUE TITLE
Magento2: Unable to redirect to new page from capture method of custom payment module

### ISSUE THREAD

**Issue by mohinik-chetu** [magento/devdocs#510]
Hi,

I am unable to redirect to new page (where i want form submit feature) on based of some condition from capture method of model. Similar to http://stackoverflow.com/questions/21753859/implementing-3d-secure-verification-in-custom-api-based-payment-method-in-magent.
Please provide a solution.

**Comment by almarchenko** [comment]
Hi, @mohinik-chetu 

I think there are more chances to solve this if you create the issue in the Magento2 code repository. Because it definitely requires developers' input.
Would be grateful If you create an issue there and add a link to it here - we'll track and update docs if required.

Thank you.

**Comment by mohinik-chetu** [comment]
https://github.com/magento/magento2/issues/3257
