### ISSUE TITLE
Documentation Scenario Tests

### ISSUE THREAD

**Issue by sjauck** [magento/devdocs#517]
The documentation for the scenario tests is a bit _short_. ;)
https://github.com/magento/devdocs/blob/2.0/guides/v2.0/mtf/mtf_entities/mtf_scenariotest.md
Please extend it. 

If i understand the 4 lines of documentation correctly it is the right think for module development. The test cases aren´t so effective. :)

**Comment by dshevtsov** [comment]
Absolutely agree! Now we are working on everything that relates to injectable tests, because more then 90% tests are injectable. If you want to test your brand new module you can use injectable tests in most cases as well.

Scenario tests are useful when another module impacts to the test flow. For example, when user selects an option that invokes implementation of blocks from another module to the same page.
Hope to "extend" the Scenario test documentation soon ;)

**Comment by sjauck** [comment]
Ok.
So we try the injectables. :)
I am pleased to see the documentation. :) 

And please at some documentation for example test steps. :)

**Comment by dshevtsov** [comment]
I've created an internal ticket MAGETWO-49081 to resolve this issue.

[This topic](http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities.html) can help with injectable tests.

And there is [an issue about the MTF tutorial](https://github.com/magento/devdocs/issues/500) that you can track.

**Comment by sjauck** [comment]
Thx for your feedback.

The topic i already now and use it. :) 

The other issue i will read thx. :)

**Comment by xcomSteveJohnson** [comment]
Can we close this?

**Comment by sjauck** [comment]
@xcomSteveJohnson Yes we can close it. But a final comment will be helpfull if the documentation is online.

**Comment by xcomSteveJohnson** [comment]
Looks like the topic referenced by internal issue MAGETWO-49081 hasn't been created yet. I'll leave this open.

**Comment by sjauck** [comment]
Thx for your feedback.

**Comment by xcomSteveJohnson** [comment]
Closing.

**Comment by dshevtsov** [comment]
Added more details to the topic - http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_scenariotest.html
