### ISSUE TITLE
Feedback on page: /guides/v2.2/frontend-dev-guide/layouts/xml-instructions.html

### ISSUE THREAD

**Issue by empirewebdigital** [magento/devdocs#5172]
# General issue

## Description:

Container required attributes. "Name" attribute is set to required: no, but I think it should be set to yes? For both blocks and containers, name attribute is required?

**Comment by erikmarr** [comment]
Hi @empirewebdigital thank you for taking the time to submit an issue. `name` is recommended but not required. We have a note above the block and container tables that says:
`We recommend always adding a name to blocks. Otherwise, it is given a random name.`

Please let us know if you have any concerns or feedback.

**Comment by shrielenee** [comment]
@empirewebdigital  It looks like our doc page covers this with the note that @erikmarr mentioned. I'm going to close this issue. If you feel that's in error, or would like to reopen an issue, please do!
