### ISSUE TITLE
Markdown linting: No space after hash on atx style header (MD018 )

### ISSUE THREAD

**Issue by dshevtsov** [magento/devdocs#5246]
# Bug report

## Description

The Markdown linter reports about an issue when the [rule 'MD018'](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style) is enabled.

The issue is in the `guides/v2.3/mrg/ce/Config.md` file which is imported from the [magento2](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Config/README.md) codebase. The issue must be fixed in the codebase.

### Steps to reproduce

1. In the `_checks/styles/style-rules-prod` change `exclude_rule 'MD018'` to `rule 'MD018'`.
2. In your terminal, run `rake test:md`.

## Test your updates

1. Follow "Steps to reproduce" locally to get list of errors to fix.
2. Preview the HTML locally to ensure your changes did not break formatting in the resulting HTML (run `rake:preview`). For more information, refer to the [README](https://github.com/magento/devdocs#to-build-locally).

**Note**-->Do NOT use [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) in your commit message.

## Expected result

The reported issues is fixed.
The `rake test:md` command returns `No issues found`.

**Comment by atwixfirster** [comment]
PR: https://github.com/magento/magento2/pull/24420

**Comment by dshevtsov** [comment]
@atwixfirster, the heading with wrong formatting is still [there](https://github.com/magento/magento2/pull/24420/files#diff-5842ad70b588bf105368974bd22e4ebbR3)

**Comment by atwixfirster** [comment]
> @atwixfirster, the heading with wrong formatting is still [there](https://github.com/magento/magento2/pull/24420/files#diff-5842ad70b588bf105368974bd22e4ebbR3)

yes, it was 😊 

**fixed now**

**Comment by jeff-matthews** [comment]
To close this issue, we'll need to run the script to update the MRG topics and enable rule MD018 in `_checks/styles/style-rules-prod`. 

@dshevtsov, there have been several other module README updates recently that would be nice to publish on devdocs anyway.

**Comment by atwixfirster** [comment]
@jeff-matthews, please give me a list of modules and I will fix them.

**Comment by jeff-matthews** [comment]
Actually @atwixfirster, I was referring to some work that @diazwatson has done recently to add more detail to module READMEs. We'll run a script to regenerate the MRG topics on devdocs after the next release.

However, there IS another fix that you could make related to devdocs issue https://github.com/magento/devdocs/issues/5247.

There's an error in the ReleaseNotification README that must be fixed in the magento2 codebase:

```
devdocs/guides/v2.3/mrg/ce/ReleaseNotification.md 
```

If you submit a PR for that to the magento2 codebase, we can link it to #5247.

**Comment by atwixfirster** [comment]
@jeff-mathews, I can fix `guides/v2.3/mrg/ce/ReleaseNotification.md`.

**Comment by jeff-matthews** [comment]
Thanks @atwixfirster!

**Comment by atwixfirster** [comment]
PR: https://github.com/magento/magento2/pull/24489

**Comment by atwixfirster** [comment]
@jeff-matthews , are we ok here? If yes then please resolve the issue.

Thank you!

**Comment by jeff-matthews** [comment]
@atwixfirster, we need to leave this open until we either 1) regenerate all MRG topics and add to devdocs in a separate PR or 2) refactor the MRG topic generation so that linting skips these files.

@dshevtsov is working on refactoring. We'll close this as soon as we turn on rule MD0018 in production.

**Comment by jeff-matthews** [comment]
@dshevtsov, now that you've refactored the way we generate MRG topics, we can tunr on rule MD018. See https://github.com/magento/devdocs/pull/5563.
