### ISSUE TITLE
Add link to UI Library to Dev Docs

### ISSUE THREAD

**Issue by erikhansen** [magento/devdocs#526]
Per my conversations with Steve Johnson, the top of the http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/theme-ui-lib.html should have a clear link (and screenshot) to the http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/index.html page. 

Right now the only way to find the actual UI Library (on demo.nexcess.net) is by Googling "magento ui library", which is not good.

**Comment by tanberry** [comment]
Hi @erikhansen , thanks for pursuing this. I'm wondering if you and @xcomSteveJohnson discussed that the link you provide above (http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/index.html ) is exactly the same content as is in our README, at https://github.com/magento/magento2/blob/2.0/lib/web/css/docs/source/README.md??

I would much prefer to link to a file in our own repo, rather than a third-party site. ;-)

Let me know what I am missing... I know one thing that we *are* missing is that (if my memory is correct) we had agreed to move that last section of our devdocs topic (the section called "UI Library Documentation") up to the *top* of the topic, so that people can quickly see how to access the UI Lib. We still haven't done that. Would that fulfill your request? If Yes, @almarchenko can handle do this.

And BTW, I spoke with Chuck/BlueBovine about this, and he pointed out that the URL for accessing the local UI Lib is only useful to those developers who have the whole system installed, so it doesn't work for all. I appreciated that viewpoint.

Let us know, and thanks for your contributions!!

**Comment by erikhansen** [comment]
@tanberry No, we didn't discuss that. However the http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/index.html page has a number of interactive elements/examples that you can't reproduce in a wiki-format, so the https://github.com/magento/magento2/blob/2.0/lib/web/css/docs/source/README.md link is _not_ the same as the http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/index.html page.

I agree that it would be much better to link to something hosted on devdocs, rather than a potentially temporary external link. @xcomSteveJohnson and I had discussed hosting a copy of Magento 2 on devdocs so that we could link to a permanent version of the UI Library.

While moving the "UI library documentation" section to the top of the page may be useful, I don't think it's necessary if we have a publicly available version of the UI Library. And I think it's imperative to make the UI Library publicly visible.

**Comment by tanberry** [comment]
Ah, thanks for pointing out that they are diff. OK, @xcomSteveJohnson let's talk and see if there are additional options.  Hang in there @erikhansen, it'll get figured out. ;-)

**Comment by xcomSteveJohnson** [comment]
@erikhansen Created internal issue to track: CICD-2103

Please be patient, the CICD (automation) team has a lot of requests now, including some from us <g>. We'll keep you updated. Thanks for being persistent.

**Comment by erikhansen** [comment]
@xcomSteveJohnson Great! I know there are complex infrastructural considerations for something like this, so I will certainly be patient.

**Comment by almarchenko** [comment]
The internal issue Magetwo-44618 is related.

**Comment by jeff-matthews** [comment]
The most expedient way to make this info available is to update the [Magento UI library](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/theme-ui-lib.html) topic with instructions for generating the [UI library documentation](http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/index.html) from a local instance of Magento.

**Comment by dshevtsov** [comment]
The Magento UI Library documentation is now available on https://magento-devdocs.github.io/magento2-ui-library

**Comment by erikhansen** [comment]
Thanks.

FYI, the fonts are broken on that page: https://magento-devdocs.github.io/magento2-ui-library/icons.html

Compare that to a working example: http://magento2-demo.nexcess.net/pub/static/frontend/Magento/blank/en_US/css/docs/icons.html

**Comment by dshevtsov** [comment]
Thanks for the immediate feedback!
Did you mean the font icons?

**Comment by dshevtsov** [comment]
I mean the icon images on the page.

**Comment by dshevtsov** [comment]
Added the images.

**Comment by erikhansen** [comment]
Yes, I meant the icon images. I see they're fixed now.
