### ISSUE TITLE
Feedback on page: /guides/v2.3/inventory/

### ISSUE THREAD

**Issue by clish1** [magento/devdocs#5304]
Current Behavior - Stock can only be assigned at the website level.
Desired Behavior - Stock can be assigned at the store view level.

We have a global website and we want to show a Buy Now button based on the store view.  To do this we were going to rely on the store view.

Is there any plans to allow stocks to be assigned to a store view level?

**Comment by jeff-matthews** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
