### ISSUE TITLE
Unable to add more than 20 sources to a stock.

### ISSUE THREAD

**Issue by clish1** [magento/devdocs#5305]
Current Behavior:  I am not able to add more than 20 sources to a stock.
Desired Behavior:  We need the ability to add hundreds of sources to a stock.

We have several hundred sources (warehouses) throughout the US.  We need to be able to add all of them to a stock.  This is especially true since only 1 stock can be associated with a website.  If multiple stocks could be associated with a website we could group them.

**Comment by jeff-matthews** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
--
