### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/php-centos-ubuntu.html

### ISSUE THREAD

**Issue by dgoryunov** [magento/devdocs#5560]
# General issue

## Description:

Documentation lists compatible PHP versions without exlicitly mentioning that 7.3.X versions are not compatible.
It can be inferred that installing later version of PHP would not be a problem. Later version can be easily installed by default since, for example, 7.3 is the current version included in Debian

## Possible solutions:

Mention explicitly that 7.3.X is not supported.

**Comment by dobooth** [comment]
Thanks for the feedback. Not sure how you did it since we remove that page some time ago...
PHP support is discussed here: https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
Let me know if you find a version inconsistency somewhere in the docs. 
Support for PHP 7.3 was added today!
