### ISSUE TITLE
Feedback on page: /guides/v2.3/install-gde/prereq/connect-auth.html

### ISSUE THREAD

**Issue by brpine** [magento/devdocs#5702]
# General issue

## Description:

It states the following "You cannot delete or disable keys you created by signing in to your magento.com account."

## Possible solutions:

 You can delete keys as well as disable keys now.

**Comment by jeff-matthews** [comment]
Thanks for reporting @brpine. 

I think that at one point, you could not actually delete keys; only disable them. I logged in to my account and confirmed that you can now delete keys in addition to disabling them.

The docs should be updated accordingly.

**Comment by hellotaran** [comment]
@jeff-matthews Doc looks correct. However, it has that additional information to download access token. Which should not be there. Let me know if that works and I can go ahead and remove the same.

**Comment by jeff-matthews** [comment]
@hellotaran,

Actually, the steps are technically correct.

The sentence:

> You cannot delete or disable keys you created by signing in to your magento.com account. 

_Seems_ to contradict the first sentence in that [section](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html#manage-your-authentication-keys), which says:

> You can also disable or delete authentication keys.

I think the problem here is that this section sort of conflates "access keys" and "downloads token". I don't know precisely what the purpose or utility of a "downloads token" is or how it relates to "access keys", but that's what I think we need to clear up.

For example, after the bulleted list in the **Manage your authentication keys** section, perhaps we need to add a new heading like **Generate a new downloads token** that actually explains what a "downloads token" is and why you may want to generate or regenerate one.
