### ISSUE TITLE
Feedback on page: /guides/v2.3/migration/migration-tool-install.html

### ISSUE THREAD

**Issue by KilalaPhu** [magento/devdocs#5834]
i use magento migration tool to migrate data base magento 1.9.1 to magento 2.1.18
it run ok and have data but i can not checkout. it error 
https://imgur.com/fe8KMfP

i try change new database  with sameple data and still use this code. it can checkout. but use database had migrate it error.
https://imgur.com/ekMkES7
country it underfind

# General issue

**Comment by korostii** [comment]
Hi @KilalaPhu 
This repository is for documentation issues only, and you seem to be having issue with quite a specific technical issue not related to documentation, at all.

FYI The data migration tool has a separate standalone repository and the team typically responds in a timely manner, feel free contact them here: https://github.com/magento/data-migration-tool/issues (but, naturally, that only applies if the issue is indeed related to the migration tool itself).

On a side note, just a friendly advice: if you're on a tight schedule, you might want to look for a local developer/freelancer having experience with Magento2 to look into this issue for you.

**Comment by hguthrie** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
