### ISSUE TITLE
Feedback on page: /guides/v2.3/graphql/mutations/create-braintree-client-token.html

### ISSUE THREAD

**Issue by kakashihuli** [magento/devdocs#5925]
# General issue

## Description:
I get error when I call "createBraintreeClientToken".

{
  "errors": [
    {
      "message": "Cannot query field \"createBraintreeClientToken\" on type \"Mutation\".",
      "category": "graphql",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by keharper** [comment]
@kakashihuli I can't replicate this error. Are you using Magento 2.3.3 or the `2.3-develop` branch from the graphql-ce repo?

**Comment by kakashihuli** [comment]
@keharper I'm using Magento 2.3.2, it must be 2.3.3?

**Comment by keharper** [comment]
@kakashihuli  Yes. GraphQL support for PayPal/Braintree/Authorize.Net payment was added in 2.3.3, as you can see in the [GraphQL release notes](https://devdocs.magento.com/guides/v2.3/graphql/release-notes.html).

I'm closing this issue, because this isn't a documentation problem. Tag me if you have any more questions

**Comment by kakashihuli** [comment]
@keharper Okay, thanks for your help.
