### ISSUE TITLE
Add transaction isolation level requirement to database requirements

### ISSUE THREAD

**Issue by fritzmg** [magento/devdocs#5956]
According to https://github.com/magento/magento2/issues/8933#issuecomment-551520758 the https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#database section of the documentation should get the following added:

> The transaction isolation level of the MySQL server or session needs to be set to `READ-COMITTED` (the default is `REPEATABLE-READ`) in order to avoid deadlock problems with the cron scheduler.

**Comment by Kipperlenny** [comment]
I don't think this is the solution! Many shared hostings cannot do this, other shopsystems don't need this!

Please fix this in the code - not only mention the bug in the docs...

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
