### ISSUE TITLE
Error While - Advance Js Bundling

### ISSUE THREAD

**Issue by saigadekar** [magento/devdocs#6293]
https://github.com/magento/devdocs/blob/master/src/guides/v2.3/performance-best-practices/advanced-js-bundling.md

I had Implemented Js Bundling on My project which was working fine on magento 2.2.6. But after the upgrade (product-community-edition": "2.3.3) bundle js is failing while deployment.

I even updated the latest build.js file in my project but i am getting error while doing the bundle.Below is the error.
```

Tracing dependencies for: requirejs/require

Tracing dependencies for: mage/bootstrap
Error: ENOENT: no such file or directory, open '/var/www/vhosts/myproject/pub/static/frontend/Myvendor/MyTheme/en_US/jquery-ui-modules/resizable.js'
In module tree:
    mage/bootstrap
      Magento_Ui/js/lib/knockout/bootstrap
        Magento_Ui/js/lib/knockout/bindings/bootstrap
          Magento_Ui/js/lib/knockout/bindings/resizable

Error: Error: ENOENT: no such file or directory, open '/var/www/vhosts/myproject/pub/static/frontend/Myvendor/MyTheme/en_US/jquery-ui-modules/resizable.js'
In module tree:
    mage/bootstrap
      Magento_Ui/js/lib/knockout/bootstrap
        Magento_Ui/js/lib/knockout/bindings/bootstrap
          Magento_Ui/js/lib/knockout/bindings/resizable

    at Object.fs.openSync (fs.js:646:18)

```
Please help

**Comment by jcalcaben** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). You can also start a conversation in [Slack](https://magentocommeng.slack.com/archives/C4YS78WE6).

To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
