### ISSUE TITLE
Supported PHP versions for Magento 2.2.x

### ISSUE THREAD

**Issue by katmoon** [magento/devdocs#6465]
# Bug report

## Description

Info at https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html is contradictory
“Supported PHP versions:
~7.0.13”
“Supported PHP versions for Magento 2.2.x are 7.2 and 7.1. PHP 7.0 is no longer supported.”

## Expected result

It's clear if Magento still supports PHP ~7.0.13 or not.

**Comment by jeff-matthews** [comment]
Thanks @katmoon. Ordinarily, I would close this issue because we no longer support 2.2 devdocs. But there may be something we can do to add some clarity in this case.

We autogenerate PHP requirements from the `composer.lock` file found in the magento2 repo. Since 7.0 is still listed in the file, it's showing up on devdocs as supported. It seems odd that we would continue to list an unsupported version of PHP in the `composer.lock` file in the official code repo.

@dshevtsov, how do you feel about updating the template we use to pull data from the `composer.lock` file to exclude 7.0?

**Comment by hostep** [comment]
I would leave PHP 7.0 in there, it's clearly still allowed in the [`composer.lock` file for Magento 2.2](https://github.com/magento/magento2/blob/2.2/composer.json#L11)

It doesn't mean if official support for PHP 7.0 has ended that people can no longer use it. Certain Linux distro's still support older versions of PHP and will backport security fixes from newer versions to it, [example](https://metadata.ftp-master.debian.org/changelogs//main/p/php7.0/php7.0_7.0.33-0+deb9u6_changelog).

On devdocs, the line underneath the version support should get updated in my opinion, right now it is not clear enough if the statement `PHP 7.0 is no longer supported` means that it is no longer supported by Magento or by PHP itself?

**Comment by dshevtsov** [comment]
If we will hide it, this would turn the entire automation useless. I'd rather verify the manual update that contradicts to information from the codebase.
The contradictory info was added in [this commit](https://github.com/magento/devdocs/commit/e01debb591101b5657b2a00f99edfcaa0fa34032#diff-ba7242f19163f8e804014e98721154e1R46). @dobooth could you please clarify the source of the 7.0 deprecation info?

**Comment by jeff-matthews** [comment]
I think that's a bit of an exaggeration @dshevtsov, but I understand your disapproval.  

We have a similar case with 2.3.4 PHP support where we've been asked to remove 7.1 since it has reached EOL. It's still possible to install Magento on 7.1, but it has not been tested by Magento and Magento does not support it.

Let's start by updating the non-autogenerated content to try to provide clarity before modifying the template to exclude unsupported versions and see if our stakeholders approve.

**Comment by jeff-matthews** [comment]
What's particularly problematic is that we introduce the list of PHP versions specifically as "supported".

**Comment by dobooth** [comment]
We added the note in [v2.3](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php). With the current state of v2.2, anything left to be done with this issue, @jeff-matthews ?

**Comment by jeff-matthews** [comment]
No, since we no longer update the 2.2 docs, there's nothing to be done.
