### ISSUE TITLE
Working with knockout templating

### ISSUE THREAD

**Issue by samleeiii** [magento/devdocs#650]
I have the below code, figuring out how knockout works... It seems I can't use any php inside <ko>. So how do I access the base URL or specific URLs? Sorry couldn't find anything in the documentation about working with this.

 ```
<li class="minicart-nav-item" data-bind="scope: 'customer'">
            <!-- ko if: customer().firstname -->
                 <a class="customer-name" href="<?php echo $block->getUrl(''); ?>customer/account/logout">
                    Sign Out <span data-bind="text: customer().firstname"></span>
                </a>
            <!-- /ko -->
            
            <!-- ko ifnot: customer().firstname -->
                <a class="customer-name" href="<?php echo $block->getUrl(''); ?>customer/account/login/">
                    Sign In
                </a>
            <!-- /ko -->
            </li>

            <script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "customer": {
                                    "component": "Magento_Customer/js/model/customer"
                                }
                            }
                        }
                    }
                }
            </script>
```

**Comment by xcomSteveJohnson** [comment]
@almarchenko Would you mind asking developers about this?

**Comment by samleeiii** [comment]
Where's the proper channel for that? Magento stack exchange?

**Comment by xcomSteveJohnson** [comment]
@samleeiii Yes, you can ask there. We would appreciate it if you'd post the answer back here so we can know if to update documentation and what to update. Thanks!

**Comment by samleeiii** [comment]
I will try, it's often difficult to get a response there.

**Comment by xcomSteveJohnson** [comment]
OK, we'll help you as much as we can. @almarchenko returns to the office on Monday.

**Comment by samleeiii** [comment]
Thanks!

**Comment by guz-anton** [comment]
Hi @samleeiii 
Lets break your issue on steps:

1. About _what's going on?_
It hard to get you advice without understanding context of question.  
Looks like it's a part of some `.phtml` file. So you can execute any `<?php echo $block-> ...  ?>` command. And if the command returns a _string_, than _string_ will be placed on the page.
And there is no magic regarding Knockout templates. Just php's templates preprocessing.

2. About _can I use php inside Knockout templates?_  
*No* . Knockout templates are used only by client-side application. "No" in terms Knockout will not communicate with php snippet directly.

3. About _will my php snippet work (execute) inside Knockout templates?_
*Yes* , it will be, until you try to pass it inside `.phtml` or `.php` files. Because Knockout templates are used only by client-side application.

4. About _how could I properly get URL in template?_

On server side:
```
<?php $block->getUrl('customer/account/logout'); ?>
```
You can find more helpfull methods in `lib/internal/Magento/Framework/View/Element/AbstractBlock.php`.

On client side:
```
define(['mage/url'], function(url) { // less talented then $block->getUrl
   url.build('customer/account/logout'); 
});
```

Both solutions expect that you place this path via some variable in template.

Last note:
- You can get help faster with more accurate interface on [Magento2 Stackexchange](http://magento.stackexchange.com/questions/tagged/magento2). devdocs/issues is more about _issues_ in documentation.

**Comment by samleeiii** [comment]
Thanks that's a big help! I did try stackexchange but unfortunately did not get any help.
