### ISSUE TITLE
Verifying Recommendations

### ISSUE THREAD

**Issue by atwixfirster** [magento/devdocs#6643]
# Topic clarification/correction request

## Topic Link

[Verifying Recommendations](https://devdocs.magento.com/recommendations/testing.html)

## Description

I've a question about `environmentId` value on the next screenshot:

<img width="1296" alt="01" src="https://user-images.githubusercontent.com/13585327/74443652-375d6400-4e7c-11ea-87a9-8b1cb6eafaf5.png">

I am verifying context data on my Magento instance and I do not see it.

## Possible solutions

We should notice, that customers should install the latest `magento/module-data-services` version (now it's `3.0.6`) to have an `environmentId`:

<img width="1110" alt="03" src="https://user-images.githubusercontent.com/13585327/74444981-5230d800-4e7e-11ea-9e6d-833a958b11af.png">

## Additional information

The source of mentioned data is - `Magento\DataServices\Block\Context`::`getStorefrontInstanceContext()`:

<img width="901" alt="02" src="https://user-images.githubusercontent.com/13585327/74443676-3debdb80-4e7c-11ea-88fb-7e4f35c5153a.png">

I am using `magento/module-data-services`:`3.0.3` and there is no `environmentId` field in the mentioned module version.

But for `magento/module-data-services`:`3.0.6` all is fine:

<img width="901" alt="6644" src="https://user-images.githubusercontent.com/13585327/74447056-69bd9000-4e81-11ea-9740-23cd83495dfd.png">

CC: @erikmarr

**Comment by jcalcaben** [comment]
@erikmarr is this related to what you are currently working on?

**Comment by erikmarr** [comment]
Thanks @atwixfirster for your feedback! Because this content is specific to the EAP, we don't want to specifically mention the new version the user has to install in the docs. Rather, we will publish (on Slack) when we push new updates so users can run the following to update their install:
`composer update magento/product-recommendations --with-dependencies`
Admittedly, we have not yet made our EAP participants aware of any changes formally so your proactiveness is appreciated! We will improve our communication going forward so you can be made aware of these changes to avoid confusion.
