### ISSUE TITLE
Support custom devdocs tooling in Docker

### ISSUE THREAD

**Issue by jeff-matthews** [magento/devdocs#6966]
# New feature request

## Description

A contributor added steps for using the official Jekyll Docker image to build the devdocs project locally. However, the devdocs project uses custom rake tooling and plugins that may not be supported in the official Docker image.

## Expected result

All rake tasks and plugins work as expected in a Docker container.

## Benefits

Contributors can run all rake tasks and plugins in the Docker container instead of configuring Ruby on their systems.

## Possible solutions

Use the `jekyll/builder` image instead of `jekyll/default`: https://github.com/envygeeks/jekyll-docker/blob/master/README.md#builder.

## Additional information

See official Jekyll Docker docs: https://github.com/envygeeks/jekyll-docker/blob/master/README.md.

**Comment by hguthrie** [comment]
The current `docker-compose.yaml` file uses the standard `jekyll/jekyll` image that contains all the node and ruby you might need for basic edit-build-test scenarios. You are able to run some of the `rake` commands. See the **Access the container** section of our [Build DevDocs with Docker](https://github.com/magento/devdocs/wiki/Build-DevDocs-with-Docker) wiki page.

**Comment by BarnyShergold** [comment]
@hguthrie - Is this still an issue that should remain open?

**Comment by hguthrie** [comment]
Since I am technically able to access a container and run a rake command, it seems like the objective was met. I left it open in case someone wanted to try to build something more robust or use builder as the possible solution suggest.
But, I am fine with this closing. If someone wants to improve the Docker with a new idea, they can always open a new issue or PR. Closing... thanks Barny!
