### ISSUE TITLE
Category attribute values are not saved in Magento CE 2.3.4

### ISSUE THREAD

**Issue by neobiz** [magento/devdocs#7204]
# General issue
The value is not saved on magento CE 2.3.4
## Description:
The new field is displayed on the backend, but when we modify the value and save the category then the value is not saved.
## Additional information:
I also tested with a text attribute instead the booleab and the value is not saved.

**Comment by shrielenee** [comment]
I'm removing you as assignee @nitish-ranjan05 as there has been no progress on this since May. If you'd like to pick this issue back up again and work on it, please do!

**Comment by BarnyShergold** [comment]
@shrielenee - This issue is not a DevDoc issue - this seems to be new behaviour in Magento. I have noticed this happen on brand new attributes. You need to wait until indexing & caching catches up. What seems to sometimes happen is the new value IS saves to the database, it's just not displayed on the Admin Product page.

Now it does seem odd behaviour (and I've seen it on Cloud Commerce - drove me nuts) but it does resolve itself. even if you want to claim this as a "bug", this issue is not a DevDocs one, unless we are saying this behaviour needs to be documented? We'd need a definitive answer from one of the Adobe Magento team as to what is going on.

Personally this should either be transferred to magento/magento2 or just closed

**Comment by shrielenee** [comment]
If this is a quasi-bug that resolves itself and is not really a docs issue (as you mentioned, and I should have seen before) we should close this. What do you think @BarnyShergold ?

**Comment by BarnyShergold** [comment]
I would say close it and recommend to @neobiz to raise on magento/magento2 if they wish

**Comment by BarnyShergold** [comment]
@shrielenee - As we've not had any nos to the question of closing, I am going to close this issue.

@neobiz - If this is still causing an issue for you then please raise on magento/magento2 as it's a functional issue not a devdocs one.
