### ISSUE TITLE
inconsistent recommendations for SKIP_SCD

### ISSUE THREAD

**Issue by markshust** [magento/devdocs#7271]
# Bug report

## Description

There are inconsistent recommendations when it comes to the `SKIP_SCD` variable.

On the deploy variables page https://devdocs.magento.com/cloud/env/variables-deploy.html#skip_scd it states:

> We recommend setting this option to true because running static content deployment during the deploy phase can significantly increase deployment times and downtime for your live site.

However on the build variables page https://devdocs.magento.com/cloud/env/variables-build.html#skip_scd it states:

> We do not recommend setting this option to true because running static content deployment during the deploy phase can significantly increase deployment times and downtime for your live site.

In one section is says "We recommend", in the other section it says "We do not recommend".

## Expected result

The verbiage to match recommended best practices for `SKIP_SCD`. Right now the pages have conflicting recommendations.

## Possible solutions

Perhaps the build page verbiage should read "during the build phase"? This would keep the recommendation of `SKIP_SCD` to `true` in the deploy phase, but keep it not recommended for the build phase. It would also be worth clarifying this in the build phase documentation. I'd first like to clarify though this is the case before making a PR to fix this.

**Comment by meker12** [comment]
@markshust These variables can be a bit confusing, and the two descriptions that you mention don't help the situation.

So:

SKIP_SCD = true = do not build static content

SKIP_SCD = false = build static content

I think we could update the text like this to clarify:


**[Deploy variables page](https://devdocs.magento.com/cloud/env/variables-deploy.html#skip_scd)**

On the deploy phase, we recommend setting `SKIP_SCD=true` so that the static content build does not happen during the deploy phase. This setting minimizes deployment time and prevents  site downtime that can occur if the static content build fails during the deployment. 

**[Build variables page](https://devdocs.magento.com/cloud/env/variables-build.html#skip_scd)**

On the build phase, we recommend setting `SKIP_SCD=false` so that the static content build occurs during the build phase where the process will not impact site deployment or cause unnecessary site downtime.


Does this make sense to you?

This concept is also described on the [Zero downtime deployment](https://devdocs.magento.com/cloud/deploy/reduce-downtime.html)

```Configure static content deployment If static content deployment fails in the deploy phase, your site gets stuck in maintenance mode. When a failure occurs during the build phase, the process avoids downtime because it never begins the deploy phase. Generating static content during the build phase with minified HTML, also known as the ideal state, is the optimal configuration for zero-downtime deployments and prevents downtime if a failure occurs.```

**Comment by markshust** [comment]
@meker12 thank you so much for the info! that definitely makes a lot more sense. I'll make a PR with these updates.
