### ISSUE TITLE
NDB Cluster 7.4.* Support

### ISSUE THREAD

**Issue by rsidhaarth** [magento/devdocs#7481]
Hi Team,

I am trying to migrate the mysqldump data to NDB cluster 7.4 and I am getting error with Fulltext.

As I can see that, M2 support NDB Cluster 7.4 but when trying to create a table on NDB cluster it fails as they dont support FULLTEXT.

So whats the solution here?

`CREATE TABLE `catalogsearch_fulltext_scope1` (
  `entity_id` int(10) unsigned NOT NULL COMMENT 'Entity ID',
  `attribute_id` int(10) unsigned NOT NULL COMMENT 'Attribute_id',
  `data_index` longtext COMMENT 'Data index',
  PRIMARY KEY (`entity_id`,`attribute_id`),
  FULLTEXT KEY `FTI_FULLTEXT_DATA_INDEX` (`data_index`)
) ENGINE=NDB DEFAULT CHARSET=utf8 COMMENT='catalogsearch_fulltext_scope1_tmp';
`

**Comment by shrielenee** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have any more questions.
