### ISSUE TITLE
Ui-columnscontrols topic needs clarification

### ISSUE THREAD

**Issue by zaheerbadi** [magento/devdocs#7730]
# General issue

https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-columnscontrols.html

## Description:

I was just looking on this component to add this in my custom grid but I am very disappointed with this guide.
Do you think any middle-level developer can implement this custom component in their module?
Just 5-6 line of code and there isn't specify how to use this and what is required for this like PHP class /data provider or  class any other relevant info.
Also I have tried to implement this in my current module grid like

`<columnsControls name="columns_controls">
            <setting>
                <minVisible>1</minVisible>
                <maxVisible>3</maxVisible>
            </setting>
         </columnsControls>`
and got error like setting is not compatible attribute in XML file.

## Possible solutions:

There should be real example how we can implement this in a custom module.

## Additional information:

I have read also there docs but all are missing proper guide as of me.

**Comment by dobooth** [comment]
@serhiyzhovnir Is there room for improvement on this topic?

**Comment by konarshankar07** [comment]
Hello @zaheerbadi ..
I checked your implementation added in the ticket description and there is typo in your code you have written `setting` instead of `settings` which is correct in https://devdocs.magento.com/guides/v2.4/ui_comp_guide/components/ui-columnscontrols.html. Please apply the mention change and let me know if you still have issue with the documentation
Thanks

**Comment by Santoshziffity** [comment]
@magento I am working on this
