### ISSUE TITLE
B2B: Update the compatibility matrix with B2B versions & MC versions

### ISSUE THREAD

**Issue by srsathish92** [magento/devdocs#8091]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/cloud/configure/setup-b2b.html

## Description

Please update the compatibility matrix with B2B versions & MC versions.

## Additional information

I tried the same as mention in given documents. But I am getting version conflicts with dotdigital modules and core modules. Then I replaced the dotdigital modules with '*' in composer.json & dotdigtal issue got fixed.

But the core module related conflicts still exists, I am using **Magento Commerce cloud 2.3.5-p2**

**Example:**

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/product-enterprise-edition 2.3.5-p2 requires magento/module-logging 101.1.5 -> satisfiable by magento/module-logging[101.1.5].
    - magento/product-enterprise-edition 2.3.5-p2 requires magento/module-logging 101.1.5 -> satisfiable by magento/module-logging[101.1.5].
    - Can only install one of: magento/module-logging[101.1.5, 101.2.1].
    - Can only install one of: magento/module-logging[101.2.1, 101.1.5].
    - magento/module-shared-catalog 100.3.0 requires magento/module-logging 101.2.1 -> satisfiable by magento/module-logging[101.2.1].
    - magento/extension-b2b 1.3.0 requires magento/module-shared-catalog 100.3.0 -> satisfiable by magento/module-shared-catalog[100.3.0].
    - Installation request for magento/extension-b2b ^1.3 -> satisfiable by magento/extension-b2b[1.3.0].
    - Installation request for magento/product-enterprise-edition 2.3.5-p2 -> satisfiable by magento/product-enterprise-edition[2.3.5-p2].

```

If I update the magento/module-logging to 101.2.1 its throws MC 2.3.5-p2 requires magento/module-logging:101.1.5.

please let me know if need more piece of information.

**Comment by BarnyShergold** [comment]
Thank you for your feedback! It doesn’t seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the Magento Support Knowledge Base, forums, or Stack Exchange. To report Magento 2 issues with code, see the Magento 2 GitHub. To suggest new product features and enhancements, see Magento features and improvements. Thanks for taking the time to create a GitHub issue for docs improvement! Keep us updated with your potential solution so we may update documentation to be clearer (or you can create an issue for it yourself!)
