### ISSUE TITLE
Add more info on using selected_options

### ISSUE THREAD

**Issue by kirkmadera** [magento/devdocs#8139]
# General issue

https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html

## Description:

How do I use `selected_options`? There is a random hash stated in the documentation, but no explanation on where to source that from...

**Comment by keharper** [comment]
@kirkmadera Make sure your `products` query looks like this.

```
{
  products(filter: {sku: {eq: "WSH12"}}) {
    items {
      sku
      ... on ConfigurableProduct {
        variants {
          attributes {
            uid
            label
            code
          }
        }
      }
    }
  }
}
```

These truncated results show what you're getting.

```
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "WSH12",
          "variants": [
            {
              "attributes": [
                {
                  "uid": "Y29uZmlndXJhYmxlLzkzLzUz",
                  "label": "Green",
                  "code": "color"
                },
                {
                  "uid": "Y29uZmlndXJhYmxlLzE1OS8xNzE=",
                  "label": "28",
                  "code": "size"
                }
              ]
            },
```
We'll make sure this is added to the docs.

**Comment by kirkmadera** [comment]
Thank you. What about for gift cards? How can I find the uid for the options like "Sender Name". They are hard coded in Magento unit tests, so we ended up hard coding them. While this is working, this data seems like it should be provided from GraphQL like in the above.

**Comment by keharper** [comment]
@kirkmadera There's an example of using `entered_options` at https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html#add-a-product-with-entered-options

A query to fetch the `uid` of that simple product would look like this

```
{
  products(filter: {sku: {eq: "24-WG03"}}) {
    items {
      sku
      ... on CustomizableProductInterface {
        options {
          ... on CustomizableFieldOption {
            option_id
            title
            value {
              sku
              uid
              max_characters
              price
              price_type
            }
          }
        }
      }
    }
  }
}
```

For a gift card, you'd use a `GiftCardProduct` fragment, instead of `CustomizableProductInterface`. The rest should be easy to figure out. There's also a sample gift cart `products` query at https://devdocs.magento.com/guides/v2.4/graphql/interfaces/gift-card-product.html, but it hasn't been updated to include entered_options.
