### ISSUE TITLE
Magneo cloud dev docs contradictory information

### ISSUE THREAD

**Issue by manafpm** [magento/devdocs#8208]
# Contradictory information on cloud dev docs

## Contradictory information on cloud dev docs at https://devdocs.magento.com/cloud/deploy/static-content-deployment.html

At this page https://devdocs.magento.com/cloud/deploy/static-content-deployment.html , there is mentioned as "Even with minified HTML, each content file must be copied to the mounted ~/pub/static directory, which can take a long time" and then in the next paragraph it is said that "Instead of copying files to a mounted drive, it creates a symlink from the ./init/pub/static directory." . These 2 statements are contradictory and readers would get confused.

**Comment by manafpm** [comment]
@magento I am working on this

**Comment by manafpm** [comment]
@magento add to contributors team

**Comment by manafpm** [comment]
@magento add to contributors team

**Comment by BarnyShergold** [comment]
@manafpm - The statements are not contradictory.
The important bit is that the first paragraph refers to generating static content in the DEPLOY phase and the second in the BUILD phase.

Extracting the most important bits :
"As seen in the following chart, generating static content during the **deploy** phase is the least optimal choice. Even with minified HTML, each content file must be copied to the mounted ~/pub/static directory, which can take a long time"

"Generating static content during the **build** phase with minified HTML ....... Instead of copying files to a mounted drive, it creates a symlink from the ./init/pub/static directory.

Can you please re-read these and let me know if it now seems clear? If not, what change (for you) would help differentiate between the two?

**Comment by manafpm** [comment]
Hi @BarnyShergold ,

Thanks a lot for the clarifications. I think I was misreading it. When I re-read it I understood the content properly. 

Regards,
Manaf
