### ISSUE TITLE
Feedback on page: /guides/v2.4/migration/bk-migration-guide.html

### ISSUE THREAD

**Issue by thiagopov** [magento/devdocs#8441]
Erro 404 in https://github.com/magento/code-migration 

# General issue

## Additional information:

Erro 404 in https://github.com/magento/code-migration

**Comment by jeff-matthews** [comment]
The magento/code-migration repo has been marked `Private archived`, which is why it appears as a 404 for users that do not have access to our private repos.

@victor-v-rad, we either need to remove the link to the code-migration repo or ask the repo owner to mark it as `Archived` (public). What do you think?

**Comment by thiagopov** [comment]
ok, i await access, public, i believe, in order to better understand the migration process, hug, merry christmas and end of year to all.

**Comment by victor-v-rad** [comment]
code migration tool project looks outdated (no git commits in about 1.5 years) and no support. I believe it is better to remove the text 
> Also, we have developed the Code Migration Toolkit, which will help to port your extensions and custom code to Magento 2, significantly reducing your efforts.

from /guides/v2.4/migration/bk-migration-guide.html

**Comment by victor-v-rad** [comment]
Created MC-40381 to process reported issue
