### ISSUE TITLE
Can nested fields be used in the searchCriteria

### ISSUE THREAD

**Issue by Ahmed-Sajjad** [magento/devdocs#8678]
# General issue

Is it possible to use the nested fields of a salesorder in a GET Orders searchCriteria?

## Description:

Hi,

I wanted to filter the Orders using a nested field. Refer to the json below, I want to use the `method` field in the searchCriteria

```
{
    "id": 1,
    "sku": "something",
    "payment": {
        "method": "cheque"
        ...
    },
    ...
}
```

## Possible solutions:

I searched the docs and tried the syntax as used in the filtering field

`?searchCriteria[filterGroups][0][filters][0][field]=payment[method]&...`

but I got an error.

If this is possible to do then any help with this would be great.

**Comment by Ahmed-Sajjad** [comment]
@magento-admin just wanted to know if this is possible in the current version of the API

**Comment by bdenham** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Magento DevDocs documentation. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Magento features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
