### ISSUE TITLE
Expand remote storage authentication example

### ISSUE THREAD

**Issue by hguthrie** [magento/devdocs#8823]
# Topic clarification/correction request

## Topic Link

https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html

## Description

per Slack: i think we need to show a sample scenario for IAM and for the secret keys, separately, and in more depth.

## Possible solutions

Possibly expand topic or create a new sub-topic with a **generic** example for including the Nginx `ngx_aws_auth` module for use with secret keys.

**Comment by tdm4** [comment]
I have some suggestions to make:

1. If you use EC2 IAM profiles you don't need the Nginx `ngx_aws_auth` module. However, I do believe you need to allow public access to the S3 bucket so that nginx can proxy images without getting a 403 forbidden. You can set a bucket policy like this (make sure you **uncheck** `block all public access` first:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicGetObjectOnly",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET/*"
        }
    ]
}
```

2. The Nginx code snippet for proxying should be rewritten as follows to use new virtual hosted style access instead of path style access (which is being deprecated, see more information [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access))
```
location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
    # Proxying to AWS S3 storage.
    resolver 8.8.8.8;
    set $bucket "<s3-bucket-name>";
    set $region "<s3-bucket-region>";
    proxy_pass https://$bucket.s3.$region.amazonaws.com$uri;
    proxy_pass_request_body off;
    proxy_pass_request_headers off;
    proxy_intercept_errors on;
    proxy_hide_header "x-amz-id-2";
    proxy_hide_header "x-amz-request-id";
    proxy_hide_header "x-amz-storage-class";
    proxy_hide_header "Set-Cookie";
    proxy_ignore_headers "Set-Cookie";
}
```

**Comment by hguthrie** [comment]
@tdm4  Thanks for adding ideas to the issue!

**Comment by tdm4** [comment]
One thing I did notice is.. the new media gallery doesn't work when S3 is used as remote media. I've run the media.sync commands but there's no change. The old media gallery still works though.

**Comment by hguthrie** [comment]
This issue appears to still be valid but was not migrated to the new repository. I grabbed the information from this issue and placed it in https://github.com/AdobeDocs/commerce-operations.en/issues

You are welcome to correct, clarify, or add to this issue in the new repository: https://github.com/AdobeDocs/commerce-operations.en/issues/116
