### ISSUE TITLE
No documentation of login itself in soap M1

### ISSUE THREAD

**Issue by zainengineer** [magento/devdocs#886]
Login is extensive referenced by m1x soap api documentation
But it does not have its own entry page.

It is just username and apikey but it should be documented
`Mage_Api_Model_Server_Handler_Abstract::login()`

**Comment by xcomSteveJohnson** [comment]
It is covered [here](http://devdocs.magento.com/guides/m1x/api/soap/introduction.html) in the API section. Is that OK?

**Comment by zainengineer** [comment]
@xcomSteveJohnson  
is it possible to have its separate entry like other pages
http://devdocs.magento.com/guides/m1x/api/soap/catalogInventory/cataloginventory_stock_item.list.html

so it is more detailed and easy to find in search engines.

Every api call has its own entry.
login call is used for almost every api call so it should have its own entry as well.

**Comment by xcomSteveJohnson** [comment]
@zainengineer Left to myself, I can tell you there is no ETA for getting this done. I probably can't get any resources to help me either.

If you'd like to contribute this as a PR, I will give you credit similar to [this topic](http://devdocs.magento.com/guides/m1x/api/rest/get_filters.html). Otherwise, I'll close it.

**Comment by xcomSteveJohnson** [comment]
Closing. Feel free to send us a PR. Thanks!
