### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/prereq/php-settings.html -- M2 requires ext-fileinfo

### ISSUE THREAD

**Issue by medigeek** [magento/devdocs#8933]
# General issue

## Description:

m2 requires ext-fileinfo
if you don't install it, the media file manager/uploader doesn't work and throws the error
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

## Possible solutions:

add to the docs the ext-fileinfo dependency.

## Additional information:

https://community.magento.com/t5/Magento-2-x-Technical-Issues/Cannot-choose-or-upload-an-image-A-technical-problem-with-the/m-p/449372#M14146

**Comment by dobooth** [comment]
Thanks for the issue. We list PHP that are strictly required by a default Magento instance. We programmatically pull them from the `composer.yml` file. It would be very difficult to list in devdocs all the extension requirements beyond the default. See https://github.com/magento/devdocs/issues/7960 for a discussion about the issue. But if the list is incorrect, we can make changes as needed.

**Comment by hostep** [comment]
Hi @medigeek, I think I know what issue you are talking about (https://github.com/magento/magento2/issues/16531 or https://github.com/magento/magento2/issues/24332), but that issue has been solved since Magento 2.4.2 by this PR: https://github.com/magento/magento2/pull/29671

That `fileinfo` extension was indeed missing from `composer.json` files and was a hidden/undeclared dependency, but that has been fixed by that PR. Since Magento 2.4.2, when the extension is not installed it will no longer crash so the dependency is no longer strictly required.

However, if you still run into issues with Magento 2.4.2 or higher caused by that extension not being available, could you please open a new issue on the https://github.com/magento/magento2/ repository?

**Comment by medigeek** [comment]
Awesome thanks for the explanation Pieter! 👍👍
