### ISSUE TITLE
MAGE_INDEXER_THREADS_COUNT

### ISSUE THREAD

**Issue by gsa83** [magento/devdocs#8985]
# New topic request
there is no article about how to set MAGE_INDEXER_THREADS_COUNT and what are the best practices

## Content checklist

-  [ ] The topic provides an explanation of how ____ works.
-  [ ] The topic provides steps for ____.
-  [ ] The topic contains code samples that shows ____.
-  [ ] Other (please specify)

**Comment by dobooth** [comment]
https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-envphp.html

**Comment by onlinebizsoft** [comment]
There was a section about this in the docs version 2.2 but not in 2.4. I have no idea what happened!!
@dobooth @ihor-sviziev

**Comment by dshevtsov** [comment]
I assume, the referred topic was <https://commerce-docs.github.io/devdocs-archive/2.2/guides/v2.2/config-guide/cli/config-cli-subcommands-index.html>.
In the migrated documentation, it is available at <https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cli/manage-indexers#reindexing-in-parallel-mode>.

If the issue is still relevant, please reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
