### ISSUE TITLE
add information on elasticsearch configuration, eg what user/node roles are required.

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/devdocs#9067]
None of these pages[1] write anything about creating the magento user in elasticsearch. I mean users created at this endpoint and what roles it should have[2]. Also there is nothing written about what node roles[3] are expected to be available.

[1]
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-config-apache.html
https://devdocs.magento.com/guides/v2.4/config-guide/elasticsearch/es-overview.html
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html#es-install-es7

[2]
https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-roles.html

[3]
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

copy from https://github.com/magento/magento2/issues/33578

**Comment by dshevtsov** [comment]
The mentioned topics were migrated to:
- https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/search-engine/overview
- https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/search-engine/configure-apache
- https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/search/overview-search
- https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/search-engine/overview

If the issue is still relevant, please feel free to reopen it in <https://github.com/AdobeDocs/commerce-operations.en/issues>.
