### ISSUE TITLE
Docs Reference Section that No Longer Exists

### ISSUE THREAD

**Issue by astorm** [magento/devdocs#924]
The following page

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-apply.html

References a `Stores > Configuration > Design` section.  This section no longer exists in the 2.1.x branch.  Magento Inc. moved these sorts of options into the new `Content -> Design` section.  This page, and any other page, that references `Store > Configuration > Design` should reference the correct section for the correct version of Magento.  You'll need a SME or your best judgment to determine what those sections are, and if your content needs further rewrites due to that change.

**Comment by hostep** [comment]
@astorm: the documentation for Magento 2.0 is correct.
You should check the documentation specifically for version 2.1, over here: http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-apply.html (notice the version number in the url, and the version switcher at the top right ;))

**Comment by astorm** [comment]
Ah ha!  Didn't realize you had that implemented.  Only other thing I'd suggest is Google seems to have the following URL highly indexed for that topic

http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/themes/theme-apply.html

and this URL redirects to the 2.0.x version of the page, not the *latest* version.  Not sure if this is an oversight, or a deliberately preferring 2.0.x due to the size of your install base.  If the former, you might want to fix that link (and others like it) to point to the latest page.

**Comment by xcomSteveJohnson** [comment]
@astorm That's a good point. We have a way to do redirects from any page to any page such as, in this case, when the URL changes.

We should review how these redirects are done and update them accordingly. @tanberry @almarchenko

**Comment by hostep** [comment]
Just an idea: other documentation sites also have the latest version available using the `latest`, `current` or `master` key in the url, instead of the version itself. Examples:
- [https://docs.akeneo.com/**latest**/developer_guide/installation/index.html](https://docs.akeneo.com/latest/developer_guide/installation/index.html)
- [http://symfony.com/doc/**current**/page_creation.html](http://symfony.com/doc/current/page_creation.html)
- [https://laravel.com/docs/**master**/upgrade](https://laravel.com/docs/master/upgrade)
- ...

So whenever a new major version is released, you'll have to point the `latest`, `current` or `master` to that version and all the pre-existing links to those pages, will show the newest version of the docs.

Maybe this can help accomplish what @astorm suggests?

**Comment by xcomSteveJohnson** [comment]
@hostep We have an open issue on this. CC @jcalcaben , @belbiy 

The challenge is, our documentation is hosted on GitHub which isn't a web server. We can't set up rewrite rules. We'll have to get creative. But it's a good idea and we need to implement something like it.

**Comment by astorm** [comment]
@xcomSteveJohnson If only you were using a static site generation tool that's capable of publishing to any sort of web server, and not just GitHub ;)

(I know, I know, not that simple.  Dropping of this thread, but good luck!)

**Comment by xcomSteveJohnson** [comment]
Don't count out that possibility either.
