### ISSUE TITLE
Feedback on page: /guides/v2.4/install-gde/prereq/php-settings.html

### ISSUE THREAD

**Issue by sgonzalezmangana** [magento/devdocs#9246]
# General issue

## Description:
When clicking on "additional steps may be required." link on this page https://devdocs.magento.com/guides/v2.4/install-gde/prereq/php-settings.html  it opens the link on the same page, it should be on a new tab so we don't lose the user from DevDocs.

## Possible solutions:
Open the link on a new tab

**Comment by BarnyShergold** [comment]
This has been discussed and it turns out that adding {:target="_blank"} to make links open in other tabs/windows is now deprecated and not being used going forward. Instances of {:target="_blank"} are being removed as and when possible.

Therefor the behaviour of the link in this issue is actually correct and so the issue will be closed. Thank you for taking the time to report the issue.
