### ISSUE TITLE
Advanced Reporting 404 message Magento 2.4.2

### ISSUE THREAD

**Issue by davidduong90** [magento/devdocs#9247]
Feedback on page: [/guides/v2.4//reports/advanced-reporting.html](https://docs.magento.com/user-guide/reports/advanced-reporting.html)

I have configured advanced reporting for my sub domain https://magiccart.io/tpcm2/

![Screenshot_2](https://user-images.githubusercontent.com/39608917/141154772-7c4d3609-5364-4e60-b3a5-381196a99404.png)

![Screenshot_3](https://user-images.githubusercontent.com/39608917/141154798-dbcbe530-b786-4914-acb3-76d0b5811eb3.png)

I have checked the cron log, but it seems to work fine.

![Screenshot_4](https://user-images.githubusercontent.com/39608917/141155165-5793e4d0-bfa9-4658-8858-0cdea67a1a28.png)

![Screenshot_5](https://user-images.githubusercontent.com/39608917/141155195-3e259f58-b1a5-4215-a237-7720ad797d9a.png)

I can see a file data.tgz in path

pub/media/analytics/35d7d8b6413879706762dc5bc96ff8f199c0ad8c585664ed0c00d81513fb3bfe/data.tgz

But when I try to open this file, it shows a bug.

![Screenshot_6](https://user-images.githubusercontent.com/39608917/141155616-ed808780-7ecc-4b26-a192-971cadb311a0.png)

Please help or have any idea will be great. Thank you so much!

**Comment by davidduong90** [comment]
@magento I am working on this

**Comment by davidduong90** [comment]
Thank you so much!
@magento add to contributors team

**Comment by BarnyShergold** [comment]
@davidduong90 - Please can you explain why his has been raised on the DEVDOCS repository? If there is a bug in the application then this should be raised on magento/amgento2 or reported to Adobe. This bug doesn't relate to the documentation.

**Comment by davidduong90** [comment]
@BarnyShergold But I can't make it work like the guide in document.

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Commerce developer documentation. To get answers to your questions, check the [Adobe Commerce Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Adobe Commerce issues with code, see the [Adobe Commerce GitHub](https://github.com/magento/magento2). To suggest new product features and enhancements, see [Adobe Commerce features and improvements](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/idb-p/feature-requests). Thanks for taking the time to create a GitHub issue for docs improvement!
