### ISSUE TITLE
Tutorial should specify version number

### ISSUE THREAD

**Issue by AboElnoor** [magento/devdocs#9268]
# General issue

https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/modify-image-library-permissions/
Available Magento version not provided
## Description:

Showing the Magento version for the article is important for us to check if it's compatible with the current installation.
ex. this article does not show if it's compatible with ver. 2.4.2 or not.

**Comment by Viper9x** [comment]
@AboElnoor The feature "Modify Media Library folder permissions" is available since Magento 2.0, I think it works with all magento 2 versions: 2.0.x to the latest version. In that case, we don't need to specify version number on the tutorial.
@dobooth What is your thought?

**Comment by AboElnoor** [comment]
@Viper9x Thanks for your answer, but I'm thinking about something like what is existing in the PHP manual

Look at the following:
![Screenshot-20220106155933-358x100](https://user-images.githubusercontent.com/16509141/148394371-e151e371-7346-4791-9e91-bb91b42b57b1.png)

I think it will be extremely useful.

**Comment by Viper9x** [comment]
@AboElnoor I do not understand, what do you mean?
If you want to check Magento 2.4.2, you can see this code for example:
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Catalog/etc/config.xml#L68

**Comment by keharper** [comment]
@AboElnoor We don't maintain separate documentation for each patch release. Instead, the docs reflect the code as of the most recent patch release, unless otherwise noted. We do not have any plans to change this approach.

I looked at the history of the page, and it appears we updated it for 2.4.3-p1, due to some backward incompatible changes. Previously, the configuration was done in a `di.xml` file.  You can find more information at https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/#media-gallery-folders

Given that, I don't think the tutorial would work for 2.4.2.

**Comment by Viper9x** [comment]
@keharper thanks for the information.
Bonus on @keharper answer: the feature is also supported on 2.3.7-p2 https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/#media-gallery-folders

I've read the history of the page, @dobooth just updated the page to support the new changes in magento 2.3.7-p2 and 2.4.3-p1: [Added tutorial page](https://github.com/magento/devdocs/commit/b7f437f52b5bdbdec3f6b98bc97237fecdc1d559#diff-ec8eed2f2fcb87948da529d404beddec8ca3ab5b35f527df0cf270144aa9bd04) 
which supports magento 2.3.7-p1, magento 2.4.3-p1, and the above version.

I suggest separate guide for magento version **< 2.3.7-p2 and < 2.4.3-p1**; and magento version **>= 2.3.7-p2 and >= 2.4.3-p1**:
the current revision is supported magento version >= 2.3.7-p2 and >= 2.4.3-p1, the revision before @dobooth updated[ the page is supports magento version < 2.3.7-p2 and < 2.4.3-p1](https://github.com/magento/devdocs/blob/031d76e224855f4e963e88df52d12e852b84a288/src/guides/v2.3/ext-best-practices/tutorials/modify-image-library-permissions/index.md)
@keharper what are your thoughts?

**Comment by keharper** [comment]
@Viper9x I'm OK with resurrecting the deleted material and having separate sections for the current and previous practices. I'll re-open the issue.

The symbolic link between the 2.3 and 2.4 versions would need to be broken. The 2.3 version would only mention before/after 2.3.7-p2, while the 2.4 version would only mention 2.4.3-p1. The content would otherwise be the same.

**Comment by Viper9x** [comment]
@keharper great. for the 2.4 version, what do you think about mentioning from 2.4.0 to 2.4.3 and after 2.4.3-p1?
2.4.0 to 2.4.3 will the same practices as before 2.3.7-p2

**Comment by keharper** [comment]
@Viper9x Yes, that would be fine.
