### ISSUE TITLE
Release policy doesn't appear in left nav

### ISSUE THREAD

**Issue by keyurshah070** [magento/devdocs#9302]
# General issue

## Description:

https://devdocs.magento.com/release/policy/ 
No active class(which can say that you are on this menu) on Release Polich when you are visiting the Release Policy page 
![Release policy _ Adobe Commerce Developer Guide](https://user-images.githubusercontent.com/17308601/147825696-0dbc41b3-4be2-46d1-865b-7b98e4066cf4.png)

while active classes exists when you are visiting other pages. for example Lifecycle policy https://devdocs.magento.com/release/lifecycle-policy.html

![Lifecycle policy _ Adobe Commerce Developer Guide](https://user-images.githubusercontent.com/17308601/147825779-d50f4c64-6ece-4555-9c9a-4fdc6f698497.png)

**Comment by keharper** [comment]
@dshevtsov Can you take a look at this?

**Comment by dshevtsov** [comment]
@bdenham @belbiy please advise on the issue

**Comment by belbiy** [comment]
I think it's because the script in the nav expects the URL to be the same structure (have `.html` extension). I think it can be fixed by changing the entry in [https://github.com/magento/devdocs/blob/master/src/_data/toc/release.yml ](https://github.com/magento/devdocs/blob/master/src/_data/toc/release.yml#L21) to have the `.html` extension.

**Comment by dshevtsov** [comment]
@belbiy good catch. I think it should be `/release/policy/`, in a similar way with `/release/` above.

**Comment by belbiy** [comment]
Well, i don't remember exactly what's the logic there, but the entry in TOC supposed to match what Jekyll returns from `page.url`, basically use the same permalinks style in TOC as in Jekyll setup.
