### ISSUE TITLE
Input for UpdateCompanyUser Graphql query requires a user id which is deprecated in customer object

### ISSUE THREAD

**Issue by devim-dckap** [magento/devdocs#9319]
## Topic Link

The input for update company user mutation accepts an object for which the user id is not provided in company query users list
## Description

Hai , 
      I am working on Graphql api (Magento - 2.4) for B2B customers, Logged in as a company admin in Client, I want to edit and update a company user. As per the Magento Dev Docs, the [UpdateCompanyUser](https://devdocs.magento.com/guides/v2.4/graphql/mutations/update-company-user.html#input-attributes) mutation requires a mandatory id field which is the user id, but this user id is not available in the default [company](https://devdocs.magento.com/guides/v2.4/graphql/queries/company.html#CompanyUsers) query. When I retrieved the user id by customisation  and check the update mutation it shows error as incorrect value. Can anyone help me in this aspect.
 Thank you

**Comment by keharper** [comment]
@devim-dckap This is a known issue, though I can't find it. Since this is B2B, the issue could be filed under a private repo that I don't know about. 

Maybe you can obtain the ID using REST. Here's a pointer to the docs.

https://devdocs.magento.com/guides/v2.4/b2b/company-users.html

You could also check for workarounds on the graphql channel of the Magento Open Source Slack site.

Closing, because it's a code issue.
