### ISSUE TITLE
Create return(RMA) is not working(Magento 2.4.3-p2)

### ISSUE THREAD

**Issue by mohitnavik** [magento/devdocs#9435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have upgraded Magento from 2.4.3-p1 to 2.4.3-p2. After upgrading the magento version, I am trying to create returns but getting the broken page. I checked the logs files and found the following error: Call to a member function getStoreLabel() on bool in vendor/magento/module-rma/Block/Adminhtml/Rma/NewRma/Tab/Items.php:166

### Expected behavior

RMA page should not break

### Steps to reproduce

1. Upgrade magento from 2.4.3-p2 to 2.4.3-p1
2. Try to create RMA from order view page in admin

### Environment

- Browser: Chrome
- OS: Linux

**Comment by dshevtsov** [comment]
Thank you for your feedback! It doesn't seem like your issue is related to Commerce developer documentation. To get answers to your questions, contact [Adobe Commerce Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets). They should be able to help you with this! Let us know if you have any more questions.
