### ISSUE TITLE
Provide more details about the service versions, specifically Elasticsearch

### ISSUE THREAD

**Issue by ak77-prime** [magento/devdocs#9488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

### What's wrong with the content?

More details could be provided about this caveat/caption:

```
Elasticsearch version support and compatibility for Adobe Commerce on cloud infrastructure is determined by service versions deployed on the Cloud infrastructure, and in rare cases may differ from the versions supported by Adobe Commerce on-premises deployments.
```

### What changes do you propose?

```
**Caveat**:
Elasticsearch version support and compatibility for Adobe Commerce on cloud infrastructure is determined by service versions deployed on the Cloud infrastructure, and in rare cases may differ from the versions supported by Adobe Commerce on-premises deployments.

For example, Elasticsearch 7.11 and newer are [not supported by the Cloud Infrastructure](https://devdocs.magento.com/cloud/project/services-opensearch.html)
```

### Anything else that can help to cover this?

The content at the top of the page says:

See [Search engine prerequisites](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html) for details.

**Comment by hguthrie** [comment]
There is a link to Cloud guide about the service versions. I don't think it is good to focus on caveats at this location. Mainly because that opens the door for the many caveats that used to exist in the service support table in the Cloud guide, now removed. The Elasticsearch page in Cloud guide specifically states the supported version. Closing this issue.
