### ISSUE TITLE
System requirements are out of date with the recent releases.

### ISSUE THREAD

**Issue by damienwebdev** [magento/devdocs#9497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

https://github.com/magento/devdocs/blob/master/src/_data/codebase/v2_3/system-requirements.yml
https://github.com/magento/devdocs/blob/master/src/_data/codebase/v2_4/system-requirements.yml

Are missing the patch tags:

```bash
2.3.7-p4
2.4.3-p3
2.4.4-p1
```

**Comment by jeff-matthews** [comment]
Hey @damienwebdev,

Thanks for the report. It's prompted an internal conversation about representing security patches in the system requirements table.

Historically, we've only included security patches in the system requirements table if/when they introduce major platform upgrades (which is an outlier). For example, 2.4.3-p2 and 2.3.7-p3 introduced support for ES 7.16 and OS 1.2, which is why those releases are listed in the table.

I'll follow up here when I have more information.

**Comment by damienwebdev** [comment]
I maintain this list:

https://github.com/graycoreio/github-actions-magento2/blob/main/supported-version/src/versions/individual.json

I don't know if you maintain a similar list, or even if mine is correct since I base it on the list here.

**Comment by jeff-matthews** [comment]
Nice!

This is how we're currently maintaining the list:

https://github.com/magento/devdocs/blob/master/src/_data/codebase/v2_4/system-requirements.yml
https://github.com/magento/devdocs/blob/master/src/_data/codebase/v2_3/system-requirements.yml

**Comment by damienwebdev** [comment]
@jeff-matthews yes, that's where I get my versions from, however with things like: https://github.com/magento/devdocs/issues/9498

I'm neither fully convinced of the correctness of my own version matrix or the currently listed one.

**Comment by jeff-matthews** [comment]
@damienwebdev, sorry for the delay. We'll be publishing updates today to add security patches to the system requirements table for both 2.3.x and 2.4.x.

See commit https://github.com/magento/devdocs/commit/a53858655710ef612096bca1088fd7fc5779b3c8. It will be deployed to production shortly.
