### ISSUE TITLE
Commando Line Tool link on magento loud panel

### ISSUE THREAD

**Issue by joaquin-becerra** [magento/devdocs#9548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's missing?

Hi, from the magento cloud project page (https://us-5.magento.cloud/projects/XXXXXX/environments/production) I see a link under the 'Support' dropdown that says 'Command Line Tool'. In this case is: https://devdocs.magento.com/guides/v2.4/cloud/before/before-workspace-cli.html

Obviously the content no longer exists, I don't know if the link is appropriate or not

Greetings

**Comment by hguthrie** [comment]
Closing this issue because the team responsible for the UI will not make any further updates. There is a new Cloud Console available in beta, soon to be widely available. You can read about [Cloud Console](https://experienceleague.adobe.com/docs/commerce-cloud-service/start/cloud-console.html) or the [Cloud CLI](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/dev-tools/cloud-cli/cloud-cli-overview.html) in the _Commerce on Cloud Infrastructure guide_.
