### ISSUE TITLE
The "--theme" option does not exist.

### ISSUE THREAD

**Issue by krisztianfyoma** [magento/devdocs#994]
Feedback on page: /guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html

I tried to issue the following command as per the example (**Magento v2.1.0**):

`magento setup:static-content:deploy en_GB --theme Magento/themename`

Deployment fails with the following error message:

```
[RuntimeException]                    
  The "--theme" option does not exist.
```

I also tried `magento setup:static-content:deploy en_GB --area frontend --theme Magento/themename`

I get:

```
[RuntimeException]                   
  The "--area" option does not exist.
```

Please advise.

**Comment by xcomSteveJohnson** [comment]
Are you certain of your Magento version? The `--help` command in 2.1.3 lists the `--theme` and `--area` options.

**Comment by hostep** [comment]
The `--theme` option (and a whole bunch of others) were only added in Magento 2.1.1, so they don't exist in 2.1.0. Maybe the docs should be updated to mention this?

See the [2.1.1 releases notes](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.1CE.html), it says:
> The setup:static-content:deploy command now provides flags that you can use to exclude or include individual themes, areas, and locales. For more information, see ([GITHUB-4294](https://github.com/magento/magento2/pull/4294)).

Also @krisztianfyoma: you should really consider updating to at least 2.1.2, since a whole bunch of [security issues](https://magento.com/security/patches/magento-2010-and-212-security-update) were fixed in that version.

**Comment by krisztianfyoma** [comment]
@hostep Thanks, that explains the issue. I will advise the client to update, I'll just do a `magento setup:static-content:deploy en_GB` in the meantime.

**Comment by xcomSteveJohnson** [comment]
@krisztianfyoma @hostep Added a note about which values are supported in 2.1.1

**Comment by hostep** [comment]
Thanks Steve! I just noticed a very small typo just above where you added this, it says:
> lang> takes precedence

I think it should be `<lang>`, just like in the table above.
Or even better, rename both to `<locale>` since that is what is used in the command above the table: `[<list of locales>]`

Sorry for the noise in this thread, but the issue is so small it doesn't really deserve a new ticket :)

**Comment by xcomSteveJohnson** [comment]
No typo too small! I can't change `<lang>` or `<language>` because it's part of the command. I did change `<list of locales>` to `<list of languages>`.

Thanks
